apiVersion: v1
kind: Service
metadata:
  name: mautrix-discord
  namespace: matrix
  labels:
    app.kubernetes.io/name: mautrix-discord
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: bridge
spec:
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mautrix-discord
  ports:
    - name: http
      port: 29334
      targetPort: 29334
