apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-ingress.yaml
  - azure-metrics-exporter.yaml
  - trichter-service-monitor.yaml
  - trichter-probes.yaml
  - grafana-dashboards.yaml
