apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trichter-api
  namespace: monitoring
  labels:
    app.kubernetes.io/name: trichter-api
    app.kubernetes.io/part-of: trichter
spec:
  namespaceSelector:
    matchNames:
      - trichter
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: trichter
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
