apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    namespace: trichter
type: Opaque
stringData:
    REST_PORT: ENC[AES256_GCM,data:ks/DDQ==,iv:tcZUl4Ox4yNtXb57wkmYb+ND1sVu7KWU6sqk+ZI10KU=,tag:zPs31bMwbHLBBvHpQiBMRg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:AAmCJhFuI/JC7C2lAKLbRV8YzGRmC76Y6ZCBkT4e9u4efp7LzWXk,iv:4Tel2JAEs+B4ykIVXP+LdrovSveGNLoUeeCIOsNJj14=,tag:JDBaNMP8Y7brWu/M1tIKKQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:yLTDHw==,iv:HUvyqT8RQABQeVF6Vb+IcFu5x16zCEY5NVxA+6rrt70=,tag:N2/OP8n/lByQ5LRDznnr6A==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Vu93Ae8=,iv:iS9bKYc/sC0Mm871g4wRHRqRpY4ae2N/aS4oI6/1CIk=,tag:+ynrd9TEjZKEfdKg+va/Uw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:dnfpeIJRrnL4i0QZEBEEPUaiqR23,iv:59Xhk0S81+9iWuXl3VYUYtBglp/TIDe/ODWG1CcRDIM=,tag:mPHWZX/iV2r2akK+Hh/T2w==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:TfP7rMw6yU3YiA==,iv:vdP34MgKGoAmbuTJ40VWJ8uIS3exoWOBy0IDZSNt4zE=,tag:5FzR7Rl9oiFT24qLouU5tQ==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL08rR0VLY21PRjNxTEVP
            RmIyYUJZZDJ6TEM2cGp0ZHlYeVVLWkp4am1VCmtFcWVxR212WHlFTDJvWUNuanFx
            dXpMS1NHbU9qekF0QzlyNEFMbWNYc28KLS0tIG1RV0Y1V1NKVnBKSGlsTEpJRkVz
            QWVybVBjckZHb3h0cXp2cGR2SEJkbVkKJNhCwHQF78JmIOjSbqlVzLMBmIxXBWGn
            UfMUX0j3vO1CQ6coflY72vsKGAJ0v/ECm+1eX0kw3leuwqyUoABIiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T10:34:35Z"
    mac: ENC[AES256_GCM,data:j6DdH6A91LS/e35dGdfIIxu9eIYlMajDjiYWDJ+zqrbirTV74zbZX8QxSBrx2HIUc1BEMXaAVv0SFU5cZQMPQ6IvCo2KgrH0KgDeX6hHI6LlaIu/upkDrDJN+jgs+rm4RixwxUpn9SPXUBFuiUp8rxkuV+Ycp0HnnLb6eMtSBRQ=,iv:uwpsjs69aUt0bt3IEAJ7dJtxodFRFt+AYgv40ECGJO8=,tag:CY7YSRJ5NvEfGtj/Mkw5Pg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
