apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    namespace: trichter
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:VLmS3VMwsUaKLvw6n0uIpul0zdvbxYDTmAqMXAJ4aC/g3hOR8/tERFXJXj+hrIbHIb1q4LgqGshlYS5lK+MkjDAC0EFAqndgWtAnS3H40spE9DLfQmh7Aw==,iv:GiofCxsBOMA2EMMxbNWEkwldo0VvFziuBQC1EwGTuAo=,tag:+XbvpiNKl+o+WTZ7u8mjfg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:9faJt3Q=,iv:b+sw25wsvIsm8fzfJfnOQRaaAKUQGuxj6NdHzv7TLcc=,tag:wdoWMSLdaNd2/gOIbmloOw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:fmAF5WVmpkEp1QmG3d0=,iv:jdMmTehzlCURVn8wgPQDjHl+QuiEUmaFqdLZKihBMy8=,tag:bv+DPvzxXPRVrSwNltbB8g==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:hafXIwq7zm4HSu1kiOFw,iv:YrCDZ8SaCSjLzOwS7AiGJlLv+fpqeCFOjhfGiKni7Hc=,tag:hOIySgs/r0ySzIbaeuwOxA==,type:str]
    AZURE_STORAGE_CONNECTION_STRING: ENC[AES256_GCM,data:k5SYNOHw/JjstD4jntdbUeTuRtFHHZErXHNU3nnESQyR6cv9uqOSefn1Ya4Z9+BytaCubbSsCbKqSRlZ2lbQFA19TJjrq0oWEpMQWtu0wipVlmDh7vFSFYaKFl1UtU3LNqwierhylxZ2XmuRemPeNkW+LVwYgp9PnGI0QcpdpADl/0GA39DsiwqgWuSMSVbZF0t1dl2wFGZjwI7HvQWrh++DkkIa7XogIbv/rzz7Lr5hx8fgkKNxViuTHs+aMQ==,iv:IS9m0GudfJp0ycZr6GISWpTC4MatwYEEp6f4i3AAVok=,tag:ej4FuVlZQXjVWMonyWZTrQ==,type:str]
    BETTERAUTH_PUBLIC_URL: ENC[AES256_GCM,data:6Mk7SQhtCEylhnlZAOoXKW0QU/QKPwv9cIU8wF7FLGcevQ==,iv:jMo1spagen1hHd2bgl5twWAnWVtrzS4QAf8JaODoOtc=,tag:DF5NjByp9WfNnIWirNqGZQ==,type:str]
    BETTERAUTH_INTERNAL_URL: ENC[AES256_GCM,data:a2nUHixCv20A/GJWKhvpTatygUlZa+mOWc//TnqTh4OJO1zzlWRB4Kmsuw0aTnugOwFx,iv:ZmoLYj1U/YfJfGthqFJX9n4lLO8jt2Cs4QPbGgOJjQc=,tag:K7KnSKrxuD2HTIjC8gWpbA==,type:str]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:9jgSwwP1MYDy4gYt8Vb2oXlo9k/g8vCkt0YOJMkj+lrWLA==,iv:ngxguhFwaj4r1FgrZBjBj78G4kH9hT6VmLNxPzSpbso=,tag:AdiEFmAe+w+2+A2nHdEKDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TkhzMHI3WURoeDBWWWdu
            UzNTNXJsZE1tOTJXZkkvK25BY1VOVkJGUWhNCnViZEdkQk5OU0dKSWN3L2JXcGp0
            TUVITnF3eXIxY1EwellITnhBNUxIQUkKLS0tIEdFa3JtdmFXTkNQQmV5dVo4blln
            MWJtR2liSlpoOVk4TkZuZUxvcE5rM00KZLtx2T3XX3pk68qCDVwZpYswuFvxx1Ov
            FmKSRDQLG++ZxSVlCh58Jy3dHNPjgSs7v+01KhNrJg23T3qY7umQ6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
    lastmodified: "2026-05-24T11:11:42Z"
    mac: ENC[AES256_GCM,data:H9kj+3+h3yymB8tPZE5xKgcK4YqdfCpC02ATKi/z8ps7HjkedNnet8mTF7rxlbFbeCbV6v8q+TQfBu+RVtRNsTPMfEzGA2aU51vocY3GMxvokvoVUFrr32tmXm6VIBKPR6QpvT2ArkPtvDkMYRiy1OhJ2YgGOHqfmKPjhSyKJZ0=,iv:ruac6AgksZN3sdLf8gDSeyj/Eq3LJQh1wyNiLViFtJI=,tag:N4D6nlvIcg7KfO2bBIiMIg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
