apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    namespace: trichter
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:p+VMEC2XgfZr3tpn8gWmb4/np2u8QAGLI96I13li2ezZwPaW5zyjqVzcxbJAK+wmKxlJIjSsHjTQUnv0IU1BSYUEunk7Du3l2qi+DKlh0ZmBFprI68+i8w==,iv:2NSuUY7lgkFq9sXEB3vqnpjNohbYh8EbhJ1uYmjJIEs=,tag:prj5tHEBfWOmK/CpE/kNvQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Ap/A734=,iv:Jhf+iOEZ+s2jWvVBQuQ6ommLKy5nDYUEA5v4vWn/hmw=,tag:D+HzoBjoyJ7h23kGe3NdVQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:E4AyzZ03mPae7eVsTUg=,iv:tsjIOl2eHu+PCnNe5dU6ccRQGvzWZkR5f834Chpjzas=,tag:wvWopF72hocMfDgZT6Z14A==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:UEUj4juPOLJBHvdoSG2E,iv:etwAGx0CtwTHW1jANi2m06PMkRSDmZZ+XVL5RJM5LT0=,tag:nCb4hd+llICKv5FM2K5H6w==,type:str]
    AZURE_STORAGE_CONNECTION_STRING: ENC[AES256_GCM,data:RU2qy3sQuThzUU7EQuxo8p8qDkvT2DPxZB8mNKX1L4y2BclbipxhCyw3ARsCm4219nuHWVZm5RBh3FdJyywLGkRSmgfLTAysmDsAWCD1gLV6cCMbnoww4HPPRtUZDhVSYa0J1GcLChfZcbiMwiXjfUoMMJeGFJ/IEKMrjbfE3AGJFLTBSGlM/JOcgg01S0dz0xw9zzj035zMuCjfPGMfXPgS5UxRLqky/gINpKa+Pd6zZgStSP9RV38ttE4Oew==,iv:s9PuC4y3dN3P5ahlec1AKD3Bz4meCrsdSbsxgnJ45ak=,tag:69s8kAKzfvbwF2tpJKWYWQ==,type:str]
    BETTERAUTH_URL: ENC[AES256_GCM,data:pBiPl4sqIe9dSlxGHWx0Z9dbBZhP6unWrcP1RjS5Ou4CU7XUYVxZ,iv:3B92GS24FGEGxRPQXHTENrpeXTgPMqWnrlU5jJ+NX44=,tag:dWA/WbOArlQQLAaQ+lrOvw==,type:str]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:nwwosyHqlHIV4NSRMHQ/cVmhZ54k4sNXNw859h28/S6a34ksZ+78,iv:8lHCJMspfFQ758U3yGYdMw5sAXnUv8ZTE3zwPf/7gX8=,tag:H5o3Pa7isT6y0GMS9Mf+mQ==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTElUYm9QT1dHbG4vbVdt
            OHg2MnFocmRFS1plZFpidUc0cjVzYnZYaG5JCmhaeldhR1RUMXdHZ3QxREdtYWVm
            SURKd2NnUlcwM2srdEo5N1BXRTRWSUUKLS0tIE5TcGVDT3lMS0dabHlEVnAvaHc1
            aHZ1eE9icFJPdkYxTVM4U1h2eVkzS0EKfgD4GG4rHnKN8lkM5+x4HAE4AKRaXqp2
            QWnxqrMdtzXDHm87Y/AuNY7l37bbNF+T66uL2vn5HOyfRE8wO79V8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T10:45:31Z"
    mac: ENC[AES256_GCM,data:Wj9YVirXY2YjfKYSm+4qHXkBF50KAyAy0GGr7vKkAsr5J3+W+tkBcEY5dg4KendnN5oz/wrx6ciXbQfT/mcJTQ4HKhthb4l6mMAtcljQLUtnRgm1oyCpOjahcuv9xntI0+1P4wqqQ6rhkL8DAAJbXNb/D79fg8BaQqTxti12w0s=,iv:qRdUll4dQPoPggRNjWt6fiHd3nhaelnQGScW4XHjh0Y=,tag:n1OS+ffl7YuCk/k2BMnapg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
