apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: trichter
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:aSoTUKqKnrdrZ3c8Dkr2ZoUk+0zEO8hSXMWlYTs+bWZEfl6GsPBevgbUr7h8DBzekv3w6hzmv0ABXOBZuKY6CEox5Z4157sbZPOFqXDrSItKMcetqX2TO2LuWHa5sp4r/Dnz3B1pg873JMyWpn0=,iv:AnoDLrCSIW3XsBAL5TlaLjP3JtkQ00ssbXTBY9FM464=,tag:dcGw+YZ+eFnfjqnDMQMP+w==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:ScX9RLqZiGcDM+Xk9yYHJsxwwvZi0BiugIoYTK+Z1nw=,iv:B0kizBYHdYj1NnGkzKkIsY4LHGRGTPyAoXFFUtXIRY0=,tag:gkT8PiqJQLl/AaChhU9ZGQ==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:ks7/HWeyQ+Hc1fqr8XmMpOa5gosHNFSugcCfbWkF2zZvbHU=,iv:H9O0lT9xDWAL5hjy38M66RCEH7EPr7wYO5tlACdAaNY=,tag:BxAwB1h6oMNcVK1QPsQiuQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:uSd3pNkIPautc0d2LMxB6ZvF1YEZK6mUhx1yfQyooXQvWFSVpkWtFsXsQOeMozHlVB/SPUxESfd+3IJT7wwwGPHl+mEDG/cJbn97cJcSGeS8pboUExAHSdMWwiu1nXo=,iv:p1rC6iVMJF/a50Z6vTJ4i7wAlZL2hAUC3HV0ZiOxvSA=,tag:Oo9HVC0p2y7NYDZmrM61gg==,type:str]
    SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:4zTAMEMOvPEZrM7ysqcVwroNuGoku7/diwX7KF4uJXxt7uJhuzv+hm+XdlEAQJmVUmgHAHys5rkDekQ5Yu92J4xuXN1f7+dAT24IKWsChPDimLJJFoCiDyzuD+aw/NWDQFHb2MgcIQ+wEuYfj/YDnhax3FI5c9mIkJF2T21iQUf0VLxEfx9avbzrkqh5hoNYaWeRLKQHn4So5Y1cdNRjAcDVggq4kZOZR6faWtw8gt8UtHlai94PKw7iZgz7cIM=,iv:DtQnM3B6ABinDbDfppPdKS/upM42+4QlR6oYUo1Md6o=,tag:XLPjUT2IVB7VLsPMn8Ls/g==,type:str]
    AZURE_STORAGE_CONNECTION_STRING: ENC[AES256_GCM,data:vbyko5KiAP+F9ydNPRj/hOxFLaiZa/lnKdMHvTx6AYqy/oPVaCOLoz9s/P9FtfqIWWGWqYPShraoqTUT6s3Q9OTmRToKoZlpECflTKXIdEEkmyjVgcaoB8Cz2FxhLrYsfihun40Zwau8Stq/IaTN+YcdfLn/2f0jEw/f2phITXYx61lD+IWETO1K4pYGilcR3eh2zLk9cKE3GkixVInuZ0dm884tCkYEuo/XYeIPIph4NfKC3zk2ZjVYqgmhpw==,iv:oTgNUkxBx2Hvum+Mz0MTApdpEZ48knPKo4UesBcDFEM=,tag:s/0oGcRMicX0kE29DyEGYA==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:67E2bT2YO7amJG2MnjK+,iv:vcXl5w49GJgSncsmNopRIM2WwHgvs3R2ICv6Fyk3w9g=,tag:Hvg9xcP6Lm0tmvc7zn8Olw==,type:str]
    PUBLIC_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:n32NssPcUBTGOJbSbRa6xGQWwB/rcHvNEGETmAHh8RpS1YjoqiYro93F9KbUJb7crlXBtGR9W8EKL3F/T6lbnT0QhGQdik8q,iv:LpMP+cwZIxBB/+N+NmfXfBQvmX9sxResuLkFLi7auak=,tag:tOdrPxiTN5X16pImKEFFGQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:xiqISq7GmodHSMMr2ntNh30ibrbI4VJmysJVDG7oKQX4Z7o=,iv:fpcBBTEMALayyf3XLLKJ6EzOAHXE6M2OpZ/jOyw/GMY=,tag:/2jlXV2PX/OokYcPaKIPJw==,type:str]
    PUBLIC_IMAGE_BASE_URL: ENC[AES256_GCM,data:fZFyAVkrbjSoR+MpmfiE3lo0duI+PY53OCAvVsZTdzO8hYZHWLi6KCqLfEmC,iv:IKyIJlpbAdA6BR4LsqzuqA38o9b4FdYGxBzHxwRANBU=,tag:hNpb/Pcn1LQO1UMsKGKRHw==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYVVTWWE1TXkxcG9pY3p6
            MzVvSFRKL1Yya3RNcXhNNmhVcklENm1ucFNFCmtOOGllY2hNQjVjeTA1aldWam9T
            T3FxT2MzT05COGp1VU40QmlDN1NrMm8KLS0tIHdTTFBkSGQ4SDJZek5CRDYwTWlT
            UHlPS1VEZUZ3T2xxMVBRMHMzQklYdGMKEBcC6nWy0RY7WCB7N7ruoxNa8EcqDJN2
            UfKt8vBlw6VKTDVPrKZeagPzlPE0O4cWUDH9LKE5Wb8QvMrHLnLuWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T13:01:41Z"
    mac: ENC[AES256_GCM,data:YXroFKgep6ThFT4qA019ieBhuUq+2qaRFKcsL0PwisbQArAtaP/xW+cqPfIfU3xfhmSvGGlB1uwvDMeklsejg6Yf230t3YH1OkgK07P4rLTMl8xv4DcDYPTuR/Y6NiyrH/7RvUSjmijUHzcT8V5M449nUZbrlVIWFb7bqUe+6SM=,iv:BdLo58NZVDDFDYJkfdVBP9KWBJ1OAxGUGwhrteJ/mS4=,tag:0NIoEwSjd4qaYnPT5hCUkg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
