apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: trichter
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:WkoVzFVELHvsUuqMnmaPVu/NwuyqFD0+M/bcOFXB7m1+WGdYWq4qPca2Ueyi5bUi5hU9vo0rTgaub2fswom4ulpoE8y1Kr57ZSj6WS4BkEOeeS/Gxt9YLErlruteM7V/Q65JzAqofvtC3V0CiRM=,iv:WGqm0l4+fcdV6ohJipdQSdm9QRB5kPhpryMr2cZ46xQ=,tag:lLTgOjuMy8r35MV2RheIvw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:KpWpIJ1Bj3NrCGZfOS3rLKVN8+sSFAAMbEDeLkkz94Q=,iv:uFL4lYOSugDGG/wJfK0ELZXfmq5pmJLjiSbaWZpDC90=,tag:B7R+WNNi5XVvn/Sx5Fmz7Q==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:mOpWeGkEamAif/eRH6p22uEoeAMTQ55cZvvQ6Rlij47W10Y=,iv:8P/KdDwm//CjbVMW0vEBdOaCFWpk1A135hRPYYNTZTg=,tag:y7mzvIkxg9FD8/NzpucDpQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:OOWAL73oMh7cgNJUcosh7x47ro57oBY0vriNX/hVbK2a7LDbwNoobiSfiXt4c/JHM/j4HENhBFXAFK04doSfz9ToFV0wWkXAhth/bpYrnxFWJwTFxmHGnQ0Ssin5hcE=,iv:bstDCMhY7jwedDePXpEtbm/jnlBFm2g7qP3+TF5+6WY=,tag:cpZOg+MBlQJsSy0bcYmUXA==,type:str]
    SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:zM0bcAsvh490cZBooIfnxPPQ9c19RqubsJ8gXI4/eK3wOxDXJxwekOf1XJS6qf/lbhBnkHh6v/yvtZHzLUFTTd5ND1Vr6BRDEAlvGnGZMMlxhJ98QdSNjVoyKK593qjQbqTcCtj+qDkm/wTro6CJ4ryVitDOVC5PmIJChf7miQPkTiFFHaPsOc68Q/ZpAaZd6/5UoMrfhxcbsLupoXxIkppnViprwj+5t5E0RgW6DO5XUvJcq59/w5MYvbnBao0=,iv:AcKxoEfjkGaU1hkz1D9AuKEGJEbwHd0R3HehjPHBBQY=,tag:XnST/FQrXjvWKBX8yWuAKQ==,type:str]
    AZURE_STORAGE_CONNECTION_STRING: ENC[AES256_GCM,data:8jGANIjJRfDgfC9o7Co91LKkQ1YPD3tMKasNiK4+/pyTQY7+7uvHfgFAQjrLhW5R7Ab4QAgVGyG4bDvhvO+YKCyDn5ljEDQWA+aP5rhZANFM/9eqyG5byD3F8zYO2fzrRJ4f/mMVjjR51uvJYKfsH+CfaCrpvYcUz2OKhj2YIezDA8vyTcftqrz/BPRx0i2idNauyiK6OCYOS5VELtvgkNifnrJOrYILh8xQTL/k4oG3bDBRWd9l7ayc7RXQBQ==,iv:+6DaYQ7m1yEbznb12eBY2sLjuLfoTriXxZzNhPKBLKE=,tag:PqrSH16sAGJWJBFTrNnb0A==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:KCduFG8G3cvC4nKBFkBT,iv:L981ud/MNMGkZnLzWXD7syx9HKfpViqzpUlF+n3/CWk=,tag:Q+EPA+fl1ex1lklJfGQ3Dw==,type:str]
    PUBLIC_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:A+x7WLEhH7DboKLPRu9P9iyGF3E8v3nvuUvCUWOIEf6cIkz/RWF8bC2+6OUpOAjDRQhGlutA+ck17aaUNRDrHtNoWjz0GbyZ,iv:WT0DE5vfx2DvZPnn/1XqzSk0xEEJxnLuQYzb0goWoKM=,tag:ci68hSdrObxQv6PXLRl8Fw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:ojeXTFXIERYeSuu9CBI91kR3xoHar5TFLPKT+MPyYs74/c0=,iv:MdIYua6sRWvNZ7ohBUyc5Frw+e/bODITkO2kSfFSwHU=,tag:R7hhN3DUS6atbSyKKn63qQ==,type:str]
    PUBLIC_IMAGE_BASE_URL: ENC[AES256_GCM,data:zHic8lFCerbEk6tTlEJJ/rXEEnbv/ARxUhdjxPP4eIly06n8OGwV4YOQoPWZ,iv:oeHlewG5M28E4AqvJW3s8x4lrQIhmc6lDwJYb9M9rAw=,tag:ZaxItcjr54tHJAogyHlUEQ==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZlFRcnc0cXlpQzRXQXdB
            L21BL1NOeVZIR1R4VEZwYzRUOUVXQjdBRkQ0ClZnSzVPbWtpVXZFTGVENFp3UzND
            S3hwZ1h2OGdLRkw2Y2ZPUGhzTGRBQ2sKLS0tIE5yV1htRWVBV0pZUmZUUzlReDVO
            MFV6N29Tdjg4NkhuZ3lmME1iSzcwY3MK7/6jbg3Dj8mCwOjqVPrSB1SqXQsQXfCo
            f1TIA84eZjVBhrinB9pojpxireBEtuMpBh1jfMVyYwqtIk5NIHPj8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T10:34:35Z"
    mac: ENC[AES256_GCM,data:XJLr2IqvablMUBved6NzbJK/AM4Fx3xW8BFtBNnSyLESrvre6I+W72GEpy2BFOnjXkyycBvj9HMXuSADpPRLguycZ6AHUsAj/IV6CH79CBCTFH9jgmN/klhYk9Ykp5iOLBkHeiaeOqCkSo3Mv6T+uDuLNz6VOfwCK/BDMppOFKs=,iv:YxCM57DnWLj2nQlFjJ+Tr/XNxDE/4BvNY5h2ZM9/zUc=,tag:LmBQHSwVKhvUH0DIEX74dA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
