apiVersion: v1
kind: Secret
metadata:
    name: traefik-secret
    namespace: kube-system
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:q/uLgpz3vYybV31tfo8uz6TMxPBsb5zkLs1vHZ9YlL8KAO0R2NHVJevfOw==,iv:FomIdI5tnPvBoBt9NZYvgXwaWjvOoZIx5JKPQv45WKg=,tag:SlvM/h489Pt1ZaRTt5X69g==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyalVrQ08zbytqRmZBdjlN
            N1lsckFxMTZ6NUNZOXBvekpIQXNPYndYSmpRCnNjZlZWZDQySmtyUmxPQUM2dmlG
            djhSMi9nNlJpWjdaQVloZVhDZGg3ZTQKLS0tIDRZMzkvZVhXNEcvUXhKVmg4UUZl
            eXd0TEEyTUE0QnV3bFZ1M3gyVkQzUmsK6PFfmOH16jA6vpb4/uJZsEaEsSosk0Zi
            x6HEdrQ6RO/1qGW6gK/FXy5zRoe3/oAN1SgwprLHTt2kD2/XyIQC9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:21:44Z"
    mac: ENC[AES256_GCM,data:dgACsByQwQ6YPt/N4tKZs6XlwVoZgcyAS69brUbPDhRMqDq2wmSpWqu5LIiAFCxpHMojWXssGucR4mGJIR6DMN4bj52RaaoYWUgyFW9mNzR5ms3u11zlnTxaMj0STLPxmP6YgYu/usS5KJwd/qfbp+8UM29iHxNEmClpHdyQn6M=,iv:WLvZBBz1TZavKQtVLYxVpG3DVINfKQ3p0R33RSqgrRM=,tag:R020XJXmMFGg/7Q4ErFmhA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
