apiVersion: v1
kind: Secret
metadata:
    name: web-secret
    namespace: trichter
type: Opaque
stringData:
    VITE_API_BASE_URL: ""
    BETTER_AUTH_URL: ENC[AES256_GCM,data:mdx3qEYPPPa2qF1VSQUWNnVqohL+SUEfED5hNMNEq5gqij3iYnbr,iv:veS5vmKEdfJ0be/bRZkq/RCfy3HtU88phtxr29Ons5Y=,tag:85T7206WZRws2wbhAiFEUw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:jyg/i32JWreei+XBSKzuYxv26vTKPz6kNuVRa5TJeviOqN0hjK1bxWaMgCI39e8n1e5L7BqoLxB7aWMzkFBEVw==,iv:4tQb3PEs4sUI8TXZqcUPqKSxUYDSbqjykSOYYY+n3Ns=,tag:Ll66QNqK6qUlZesXuYu5QA==,type:str]
    BETTER_AUTH_API_KEY: ENC[AES256_GCM,data:f0+zftWAequQyUx24ZCNdKwD3dcRG8PHz4Do6hPt7Gh2QiI=,iv:RpSeI7jdKoHHG2DhHPatRCQJdKUxqsqFzteCm+u3izM=,tag:aX/UM1L59VzRTKSrrBIKDA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:9GUlPo1j6k18cQnf9HYuEoN6ykTZ7z6FYn/vH2T28daoCKiBOM7zbaqaAJV+FG2a02tJ4Fi6ffi4bbRqD+U6ajIUBXD5SoCOvDZT/Z/aoCRuJ4WulqJ/R5oBkCVGquFFRA==,iv:DvCJgDUHQtT1aoldLEKCjJgROzwdodbhUhEc1b0gL1I=,tag:K+nl/WWRDO6LQHMUAaqLFw==,type:str]
    TURNSTYLE_SECRET_KEY: ENC[AES256_GCM,data:foS79zJh8NOlcQgE2cmA+26fgraj4m4HFXup95Tao2mRf5c=,iv:r7tYW6/U9FadvbM+h1PMfLIkncK8NY7Qc31JZYbKTpI=,tag:0yPeNWfE8rGWPFyVNkFZKA==,type:str]
    VITE_TURNSTYLE_SITE_KEY: ENC[AES256_GCM,data:lMuFAc4NCAbZ0/+C9ewdc8y0Sa1fRJC8,iv:zsIAXNgEorBAr1Q1dodJdk9+xTJ6sNp75C9DSJcLzCc=,tag:IlolgXY/3Xi/sYZJR+MITA==,type:str]
    VITE_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:LL1upTVz9tlC/qRNTTcIhzGMP72yvVp3H9qU77AZgZxdRm90UIF2B8YanB0GByD+ZuUCwK3erLfXT4l3GmXjO72U5xCgphCq,iv:yCW5KePgufPWW1FuUJbj1WVmZ0SK0p94107S7ooVamI=,tag:FAmz613lJH7yueO2BxR7ug==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:VmWmCQdk9sU5YIfven+w//QhgapOtovo7WpAEibf5m8IBL8=,iv:oVtHUgK0GCVT03hUXjC9MNJIlhBcXxcbpLUdQwgbWIQ=,tag:7PMIpTWO/LSN4ImRGu43JQ==,type:str]
    ACS_CONNECTION_STRING: ENC[AES256_GCM,data:j0vqtO1j/D3DcuD7CSGMfZ8xZCLfRYEhszTxmShhOViOcXhbNjsZfI094ayj4Mn4MZW9d4QO3DOt2MgiQMCHW3OsmMG2foxcfrsterIuf8aUSVfkdjvnpGsbkHrrndJnTO2NU/pm/f/JB/IlpA7zmHE4BXxxYDU9D8PN5iVvBtdXCtYgMiHV3PKhq4HSf3AfhjsvEr8WI0C8t+lr,iv:OhtiwlRENyc4R2jZDtn9c14UCF6Xv3aBeeRuvBjltvs=,tag:xpLWDpDZti9F9quEvceoeQ==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:3vZT7sVh+uryQiAjBWBnpCuyQ/rs2c20N2lyMg4j3VrH9Q==,iv:quzgk+n1wbB2cvyi53ywqyaHISu1pDebdI723Ulup58=,tag:1jzzGbaIQxVN9ral4inkXA==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQjlDS0tKRE5VUDRvSzdq
            Z1dzSHVxZFJ0dzBVTW5VTUhBWmhrampzZ0I0CkgrUUxKRkoveTBMbGl1Wnp1YitR
            bVJxdzhaQjhhWGVHZkdIZFUvN2Y2YlEKLS0tIEZGMmo3d0hOUTFLcVZPSmlKZzNF
            Sm9FQ1JaR0N5TnMyTVA3SnhxcXZseTgKgLCFr9e8K4ntdQAOwpwUvFMz7uy/v05G
            XxUDNhc636mHikR8HlPA3CcgvlAjPjhE4rXEWq9ZYeCfgf2nenc9kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T08:57:24Z"
    mac: ENC[AES256_GCM,data:MvN+ftk+7apNEKRMwHh9ALcz6mzXMNtylyDDNT2n0v0kP5/yPINtlK5wpuCe5hq/08eIRhZKNvBTDNpQcZFVLwfkwpcvsR5AatroLcuZL2Iu2/97W22K7pcqVJzZLzEJTbTEX7KhZu139BuFy6zOqtleHvlMAUNCEHnsuL/pZv8=,iv:0RkXyg9HaOjMVemwMefK3aSwDvDG8jzN+2AVir+729Q=,tag:Bu849L6wq3at5wb/ob33ZA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
