apiVersion: v1
kind: Secret
metadata:
    name: web-secret
    namespace: trichter
type: Opaque
stringData:
    VITE_API_BASE_URL: ENC[AES256_GCM,data:1TQxLXyleV8HJp9T4XIJ,iv:jGBWF9gQKHMaVyKWp/eMKAU4EI8xCYlattkm6043Wb8=,tag:FhQehh5HapRC58mn72I4wg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:deX7qeUPyVMMAhGKkIIuvM1FaiEOpRFGG+PqroTxPVRlCg==,iv:v7aaGz7pwSHPKpubxUrg23tBJRLC6FFzE9eap08SESM=,tag:gZGKk4AKPfChlxa0GMCdgg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:/Rl0j4+QJKB3ctNypRH4mdmSoiD/HGqt4XXjcQqptHJNjqwQQsZl5c54aIZMoqPXBrvnKGfzD9xf09PgivErfQ==,iv:bfFdEb4qpeT+PW8iEvj2QA31ixmlQTmYAtlrVfZN8EM=,tag:ooORMDKNqO41Ax2B3Okz0w==,type:str]
    BETTER_AUTH_API_KEY: ENC[AES256_GCM,data:gA4BhToZQlwRS3q92J8JX65c7jgVxCar2iCvf1b3NYu9RR4=,iv:J84X36Ry1vBjUF+8JWq6jiD+3oQXjnl7kRaREjzsoOA=,tag:zwe+lwkhsfZtsqXS2/+E8w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:7FKQRI+Zryg32nLbh5qiIxh4RaVlSrggUkY4gng7SwcyAvurGRKai4cLpTbJK2Tb8FGAqHdwzg8tQrZ9ZPwVhtAEnKcRuGyNimEbWhbsXYCjHehi7MwubJTh4mjrj7EoEg==,iv:NfKIHY1T5IBrxCG5foa+nGOPvYYM2m2B1+tNGVkOTGw=,tag:BohgpVd08S2IQIXnoBxnoA==,type:str]
    TURNSTYLE_SECRET_KEY: ENC[AES256_GCM,data:eS44KDOkjpfeVLt2jTVyyovsHL8/q5rJ0qRSJfug1zQfmZ8=,iv:4HWKAsBRmKX7OoTz0EVLNYWWbJA4NTPawdDl+vPbsiA=,tag:iXxaWrmoJ6wrdx2R1UzZfQ==,type:str]
    VITE_TURNSTYLE_SITE_KEY: ENC[AES256_GCM,data:tuocXMnkKrK42Pq27+sxROd0YKbh3j5m,iv:jS70Rw6hrdT9KS05Onnq1smPbzbXQEmv2UBEbaZZMM0=,tag:dtBQU7uG7wUbdv7U2ag+Lw==,type:str]
    VITE_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:GuYNarGk+QP+S/XCbCWtgwXv47G7FYwgsN9YzDsUE0xaT0M4dpl70WyY+7Uz0x8bhp0hlnqKE3RzuFYFYNtxXRDkGXY1HS8E,iv:jfTniMIv0mp+QxVKGWNpzjXTjWI1pxDDm18BPfU/0X0=,tag:BCnEJf8jYUcioMd9gKlwBA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:TtP8QoXxfWnUoTmRyqcCXYAY22DBWsuOHjFWDR4LTeyb6to=,iv:cwzsd1n5uQE2Z9ZWMGFL48SmSNQsawbY1nO57167i7s=,tag:PJ5AhmoDFnTv7ISk/AJY6Q==,type:str]
    ACS_CONNECTION_STRING: ENC[AES256_GCM,data:ZfiBOMXfKs5GYYc8wUpEzo06Excq1smnI4RMAt7wKTfsFMZjaknJRhLqCkw/tSAWSXER2QYBzPKtGcABT1ik0x3Q7XAmArc3CJcX8bWjIvBUJJIGYYjULXDM4YYiVqegeRLWS7rNAx4GeB+qR1HTWlzJ54DU7RVZVo4Pinl8wTrKlsesBpr634Eo3VarnTi08PKOHqQbf7pT9aO/,iv:AXGoM/Cr4gZ9sk67RZx+VgK/+XXP13avfjCqrU2Hty4=,tag:Qa1Oe+y8hi4jgTWy4pP9kg==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:wG10HPc/hxT23cnfn4fT21CyxGCLZiqwVmJBjqicQaRoSQ==,iv:Xdi8y63tLlnQ3WNKSx2v9Sb7Nq2nRLBHcxJo17FCyMo=,tag:wElYxKShOj8O6WcDx5w/Pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUU1tcGRPUUV4ajNscUNS
            NjAvdXFsSUdlcHNkQm5MZ3BjazNBYW9NWjNVCldXRUtmaU16MDhnekdlQ1lIczBz
            RUtGT0VpQzB4WURxY3J2UWNFS2ZvczgKLS0tIFVaUnVFaUN0MUltQ1BVMWFwRENs
            djhuWTFtb2lkSHcwK0wrbG9SRyt2ODgKhQvUB660cDUD384KC23j2kNR8oWGkYDa
            Nfj6oUXsAqCiz0wpjRfVRBzGmD3ZLbEKKbmh6Cq7Vr1hFV+bSrsQuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
    lastmodified: "2026-05-24T10:34:34Z"
    mac: ENC[AES256_GCM,data:KyFW6cUBZZ7xTrFvHEqdXBqv4KJO6nakGnXgdYlaYOYGlXcYcvYGDPtWFmDK/eutjdkfB45LbdtfCuYbYiBSO8z1sVtlcnJ970/R0t5/fXpMXrwsE+glfWlynY5BiPYyjkKyg2djXCMqQsbkC1BtFkbno6igyjDKAMYp3zfzL9E=,iv:Q9cfvDHfjjpp0FI7dzoVRxefX5jfCX6xjMwVFtKbv+o=,tag:+bqvbW0hPJSyEus+f0XiiA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
