apiVersion: v1
kind: Secret
metadata:
    name: web-secret
    namespace: trichter
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Q4UBlhRJFg78art/N48gswATPiFmz2FZZ67Tk4rnMQoCG/f+6qGwRxBj0Nh6Iv1YUfEOPvgmSa1lHi3GKgbO13xAuRYNOYOqYbBrsIT1FL/iGvLo+PaSfCdUvFvdOZgSjA8pU2YhtPr/OfVdgv8=,iv:xsgKBn/nHGYbvydnwuNCQUZc3z52p1ZZN+ikNbe2658=,tag:idnkr+NoIbrMlSmWiI34tg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:NIhhnLK5ppM9WEPX9XvJGdbRYR0JryxXRO+5YM5lbXE=,iv:ee0xZd35LQHIxDsJm4OBYpq4f31zfssABXGG/dWlAAc=,tag:0pHs8zuFKbJqJQOQb+EL4Q==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:b6CHwRDzBF2yTi7y3nBk5BEvqYBE4Z2sR/tCIEU67t+u5mlmAlKwuA==,iv:mbRovcZ1mduO+xxRjQFrtsEX7PRLB2ROdmJvAWw6vBo=,tag:5V3JCVT3S5SObv+cL5I2fQ==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOam1aZjJVdmdJcG5aR3BM
            ejBXZmhBMkVxMWhnSEpVd2FZRnIwa1pVYnpzCjBQSzFpaExadTZHY3B1NXV4d2Vr
            TVFYQ2FQTHprRExyTE9IajlUUjNWS0UKLS0tIDBRLzY3THBobzJ2WHdHSE9TN09V
            cG5ZVWdQQy9HYjVvYjlzcWR3TFpadlUK/RWT6fTRjXbkV2DtmYvlKSRokoLipjNJ
            TSva0KQF1KXHkWoWvM3Mpp3H3o5Ix1Kar5VDnLj46LAvFaBy6/4xrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T10:34:35Z"
    mac: ENC[AES256_GCM,data:i+1OZU0zSWB15H9vDPeV8/2H7Yr/AFooVhPsMb8/ZhX1MenEgzGhVC/ewOEUSVCpdDz5Ql2Ubv4AP0DONVAC46HSjBA8pJJZ9DuZPtelUm9bbQGdun5EBBJA8oxXPo2NGhnjvg4kcwcF0jpCi09E86Is2kL6l/+/h9GqLNYbGF8=,iv:t4NR0MWxxqaefcNJw1XNgdrDKK4iLqufjHtfwl2/3kk=,tag:bSHIBSeVDHdGBL9ZXcmGxA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
