// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createRun,
  getRun,
  getRunImage,
  getRunImageSignedUrl,
  getRuns,
  getRunsByUser,
  health,
  info,
  links,
  type Options,
  uploadRunImage,
} from "../sdk.gen";
import type {
  CreateRunData,
  CreateRunResponse,
  GetRunData,
  GetRunError,
  GetRunImageData,
  GetRunImageResponse,
  GetRunImageSignedUrlData,
  GetRunImageSignedUrlResponse,
  GetRunResponse,
  GetRunsByUserData,
  GetRunsByUserResponse,
  GetRunsData,
  GetRunsResponse,
  HealthData,
  HealthResponse,
  InfoData,
  InfoResponse,
  LinksData,
  LinksResponse,
  UploadRunImageData,
  UploadRunImageResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getRunImageQueryKey = (options: Options<GetRunImageData>) =>
  createQueryKey("getRunImage", options);

/**
 * Download run image
 *
 * Returns the raw image bytes
 */
export const getRunImageOptions = (options: Options<GetRunImageData>) =>
  queryOptions<
    GetRunImageResponse,
    DefaultError,
    GetRunImageResponse,
    ReturnType<typeof getRunImageQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRunImage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRunImageQueryKey(options),
  });

/**
 * Upload run image
 *
 * Uploads or replaces an image for a run
 */
export const uploadRunImageMutation = (
  options?: Partial<Options<UploadRunImageData>>,
): UseMutationOptions<
  UploadRunImageResponse,
  DefaultError,
  Options<UploadRunImageData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadRunImageResponse,
    DefaultError,
    Options<UploadRunImageData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadRunImage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRunsQueryKey = (options?: Options<GetRunsData>) =>
  createQueryKey("getRuns", options);

/**
 * List runs
 *
 * Returns paginated runs sorted by creation date (newest first)
 */
export const getRunsOptions = (options?: Options<GetRunsData>) =>
  queryOptions<
    GetRunsResponse,
    DefaultError,
    GetRunsResponse,
    ReturnType<typeof getRunsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRunsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getRunsInfiniteQueryKey = (
  options?: Options<GetRunsData>,
): QueryKey<Options<GetRunsData>> => createQueryKey("getRuns", options, true);

/**
 * List runs
 *
 * Returns paginated runs sorted by creation date (newest first)
 */
export const getRunsInfiniteOptions = (options?: Options<GetRunsData>) =>
  infiniteQueryOptions<
    GetRunsResponse,
    DefaultError,
    InfiniteData<GetRunsResponse>,
    QueryKey<Options<GetRunsData>>,
    | number
    | Pick<
        QueryKey<Options<GetRunsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetRunsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getRuns({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getRunsInfiniteQueryKey(options),
    },
  );

/**
 * Create a new run
 *
 * Creates a run entry without an image
 */
export const createRunMutation = (
  options?: Partial<Options<CreateRunData>>,
): UseMutationOptions<
  CreateRunResponse,
  DefaultError,
  Options<CreateRunData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRunResponse,
    DefaultError,
    Options<CreateRunData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRun({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRunsByUserQueryKey = (options: Options<GetRunsByUserData>) =>
  createQueryKey("getRunsByUser", options);

/**
 * List runs by user
 */
export const getRunsByUserOptions = (options: Options<GetRunsByUserData>) =>
  queryOptions<
    GetRunsByUserResponse,
    DefaultError,
    GetRunsByUserResponse,
    ReturnType<typeof getRunsByUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRunsByUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRunsByUserQueryKey(options),
  });

export const getRunsByUserInfiniteQueryKey = (
  options: Options<GetRunsByUserData>,
): QueryKey<Options<GetRunsByUserData>> =>
  createQueryKey("getRunsByUser", options, true);

/**
 * List runs by user
 */
export const getRunsByUserInfiniteOptions = (
  options: Options<GetRunsByUserData>,
) =>
  infiniteQueryOptions<
    GetRunsByUserResponse,
    DefaultError,
    InfiniteData<GetRunsByUserResponse>,
    QueryKey<Options<GetRunsByUserData>>,
    | number
    | Pick<
        QueryKey<Options<GetRunsByUserData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetRunsByUserData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getRunsByUser({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getRunsByUserInfiniteQueryKey(options),
    },
  );

export const getRunQueryKey = (options: Options<GetRunData>) =>
  createQueryKey("getRun", options);

/**
 * Get run by ID
 */
export const getRunOptions = (options: Options<GetRunData>) =>
  queryOptions<
    GetRunResponse,
    GetRunError,
    GetRunResponse,
    ReturnType<typeof getRunQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRun({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRunQueryKey(options),
  });

export const getRunImageSignedUrlQueryKey = (
  options: Options<GetRunImageSignedUrlData>,
) => createQueryKey("getRunImageSignedUrl", options);

/**
 * Get signed image URL
 *
 * Returns a temporary signed URL for accessing the run image
 */
export const getRunImageSignedUrlOptions = (
  options: Options<GetRunImageSignedUrlData>,
) =>
  queryOptions<
    GetRunImageSignedUrlResponse,
    DefaultError,
    GetRunImageSignedUrlResponse,
    ReturnType<typeof getRunImageSignedUrlQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRunImageSignedUrl({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRunImageSignedUrlQueryKey(options),
  });

export const linksQueryKey = (options?: Options<LinksData>) =>
  createQueryKey("links", options);

/**
 * Actuator root web endpoint
 */
export const linksOptions = (options?: Options<LinksData>) =>
  queryOptions<
    LinksResponse,
    DefaultError,
    LinksResponse,
    ReturnType<typeof linksQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await links({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: linksQueryKey(options),
  });

export const infoQueryKey = (options?: Options<InfoData>) =>
  createQueryKey("info", options);

/**
 * Actuator web endpoint 'info'
 */
export const infoOptions = (options?: Options<InfoData>) =>
  queryOptions<
    InfoResponse,
    DefaultError,
    InfoResponse,
    ReturnType<typeof infoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await info({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: infoQueryKey(options),
  });

export const healthQueryKey = (options?: Options<HealthData>) =>
  createQueryKey("health", options);

/**
 * Actuator web endpoint 'health'
 */
export const healthOptions = (options?: Options<HealthData>) =>
  queryOptions<
    HealthResponse,
    DefaultError,
    HealthResponse,
    ReturnType<typeof healthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await health({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthQueryKey(options),
  });
