apiVersion: v1
kind: ConfigMap
metadata:
  name: outline-config
  namespace: outline
data:
  NODE_ENV: "production"
  URL: "https://wiki.hauptspeicher.com"
  PORT: "3000"
  FORCE_HTTPS: "true"
  DEFAULT_LANGUAGE: "en_US"

  PGSSLMODE: "disable"

  FILE_STORAGE: "local"
  FILE_STORAGE_LOCAL_ROOT_DIR: "/var/lib/outline/data"
  FILE_STORAGE_UPLOAD_MAX_SIZE: "262144000"

  SMTP_HOST: "smtp.azurecomm.net"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_FROM_EMAIL: "Outline <noreply@hauptspeicher.com>"
