apiVersion: v1
kind: Service
metadata:
  name: mautrix-gmessages
  namespace: matrix
  labels:
    app.kubernetes.io/name: mautrix-gmessages
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: bridge
spec:
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mautrix-gmessages
  ports:
    - name: http
      port: 29320
      targetPort: 29320
