// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type RunDto = {
    id?: string;
    user?: UserDto;
    rate?: number;
    volume?: number;
    duration?: number;
    image?: string;
    createdAt: string;
};

export type UserDto = {
    id?: string;
    createdAt: string;
    username: string;
    displayUsername: string;
    image?: string;
    lastActiveAt?: string;
};

export type CreateRunRequest = {
    userId?: string;
    duration?: number;
    rate?: number;
    volume?: number;
};

export type PageMetadata = {
    size?: number;
    number?: number;
    totalElements?: number;
    totalPages?: number;
};

export type PagedModelUserDto = {
    content?: Array<UserDto>;
    page?: PageMetadata;
};

export type PagedModelRunDto = {
    content?: Array<RunDto>;
    page?: PageMetadata;
};

export type ImageRef = {
    key?: string;
};

export type SignedImageUrl = {
    imageRef?: ImageRef;
    url?: string;
    expiresAt?: string;
};

export type Link = {
    href?: string;
    hreflang?: string;
    title?: string;
    type?: string;
    deprecation?: string;
    profile?: string;
    name?: string;
    templated?: boolean;
};

export type GetRunImageData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}/image';
};

export type GetRunImageResponses = {
    /**
     * Image returned
     */
    200: Blob | File;
};

export type GetRunImageResponse = GetRunImageResponses[keyof GetRunImageResponses];

export type UploadRunImageData = {
    body?: {
        /**
         * Image file (JPEG recommended)
         */
        file: Blob | File;
    };
    path: {
        /**
         * Run ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}/image';
};

export type UploadRunImageResponses = {
    /**
     * Image uploaded
     */
    200: RunDto;
};

export type UploadRunImageResponse = UploadRunImageResponses[keyof UploadRunImageResponses];

export type GetRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/api/v2/runs';
};

export type GetRunsResponses = {
    /**
     * OK
     */
    200: PagedModelRunDto;
};

export type GetRunsResponse = GetRunsResponses[keyof GetRunsResponses];

export type CreateRunData = {
    /**
     * Run creation payload
     */
    body: CreateRunRequest;
    path?: never;
    query?: never;
    url: '/api/v2/runs';
};

export type CreateRunResponses = {
    /**
     * Run created
     */
    201: RunDto;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search query
         */
        q?: string;
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/api/v2/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: PagedModelUserDto;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v2/users/{userId}';
};

export type GetUserByIdErrors = {
    /**
     * User not found
     */
    404: UserDto;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * User found
     */
    200: UserDto;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetRunsByUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        userId: string;
    };
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/api/v2/users/{userId}/runs';
};

export type GetRunsByUserResponses = {
    /**
     * OK
     */
    200: PagedModelRunDto;
};

export type GetRunsByUserResponse = GetRunsByUserResponses[keyof GetRunsByUserResponses];

export type GetRunData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}';
};

export type GetRunErrors = {
    /**
     * Run not found
     */
    404: RunDto;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * Run found
     */
    200: RunDto;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type GetRunImageSignedUrlData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}/image/signed-url';
};

export type GetRunImageSignedUrlResponses = {
    /**
     * Signed URL returned
     */
    200: SignedImageUrl;
};

export type GetRunImageSignedUrlResponse = GetRunImageSignedUrlResponses[keyof GetRunImageSignedUrlResponses];

export type LinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator';
};

export type LinksResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: {
            [key: string]: Link;
        };
    };
};

export type LinksResponse = LinksResponses[keyof LinksResponses];

export type InfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator/info';
};

export type InfoResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type InfoResponse = InfoResponses[keyof InfoResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
