apiVersion: v1
kind: Service
metadata:
  name: mautrix-meta
  namespace: matrix
  labels:
    app.kubernetes.io/name: mautrix-meta
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: bridge
spec:
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mautrix-meta
  ports:
    - name: http
      port: 29319
      targetPort: 29319
