apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: outline
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:7gmDBwbUeBTqKrn6UqDlVYiJVMaeWFDzRdGpXaFvZFFMqAEhr/ajChoboX40QG8vDDJMDXrwgjJuGwjy0Kq4wA==,iv:o4ao/X0KuP375BhgIewKs5CVlsGHB6PVoZOepFZWHdI=,tag:aIH9y0qZB7vSLjTQpd7TEw==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:WXOq35+XyegxvxMxtH+8T9Pls2zgVeMXeq9tnUbldWbJflYL7dRSaW8JRFiEptEIQXgG14iXZX1p+Ie1lAbnpA==,iv:tvc1tTCFlQ2tI1iOywM4HQPTxB4yXROy2yo0T8GPrYQ=,tag:zHX5xROcIQsP6XyRjsHCRw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:roRqTjsWnw==,iv:r1mVRYKUgAGA0+/RmMdgpxK7rVwVhfVitw0MbL8OmKo=,tag:OJV4AvOTgC5tGkJA615Xvw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kRaJ/f00iMAqMsf7jPMUYClCp8S0,iv:ZKg77rtatGZQWqIgFAkzR854G/1ZvyhD7W0jnNQ+LmU=,tag:D+xgD9e3ZiqrAdya13HzFA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:SvI/OKktzg==,iv:6Ufo+KfT0tui028VMif/Ge8cgnMNlJjy5ilf4KGvZ9E=,tag:K233NfD+5EXOOfayA/j0VA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:bdvxsrC8NZHK63pfwLIT1wXCQZGzS66q6oRhPcjc7GaFX09MSeCiS2rAJ52hxaO5KckhAOYR3tqy6dv9BoOApsUPSaR5jQ==,iv:wHhVi5SODcJUqZ9ZzyefVhMcCBwCqZil3LS2OzzFHoo=,tag:VyFHoebIvqMuNkhRPqv+Lw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:s5faYBYfBpCuE9GVSaTCsiIsEFQgnQUkopw=,iv:A/k07H3nzpo0ojcPloMsFrJVxqiBO1DfwLhdmXw/UDI=,tag:DhNiuzBY3waz5T9urAOavA==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:zIvczFvOPAQk77JPxWxzaktF/Ik=,iv:elCd4GH7JD/dtsAm8qk3yKY1PvibZnrzrHu5y4oY5MU=,tag:OgJ5mcanU46mpvPpa4FaEg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:EQ5vkuPy/uHgbos0PGArqL4iOFidLUchkVGEepcziOhrRTLPcU2TMw==,iv:6ex7uDDotO+s0oZuTmStleg0eTYl3xbOWK7czp9qTIw=,tag:0uixVWGnxECJX+GUvvKrAg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:iFcrScDn9A==,iv:jF3usIP49N82gKip9hWHKQS3AfheXMc4RYAHbYOEHSE=,tag:BsWKUESozqo5i1gPr160ew==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:2z0dA0NZkXVi3DlkT5jn2mT8AbfNSPpTteZ/Zriq4JovJ2BlNlKXCw==,iv:wfhsXJc9uVzNM9kuNqQQV4Kp7ZqPvoErkpnaVX0Kvc8=,tag:7UHNbuI36TYGHzV66yemQw==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQnJ3UDRBRUJXM2NsY1A4
            KzFmRndEb0xuZ05rZEYrRWZoeEwzOUVPelVFCmYrTnplOTJTU25pNVlxbmxmbjFV
            N2o1WHJBWXhnOVVUeW9ENzdaSEV5bXcKLS0tIFFNOVN5TFNDOFFTSjZVVWdrM0U2
            OFU1TTl4NVEyUlhCQitxUC9hWkFpczQK5/MLscFsN5S0pfbEtAv8UabLSdusB9c5
            e7Y3FN6dxs+VJLRo13ugFvGqELPpXn7jSCMrLAICM4D1a8mQoEkSVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T11:50:39Z"
    mac: ENC[AES256_GCM,data:twqY5FsJ6MPuImitTwo1R2MvenJ5V34EWo1rx6DrW8dCG4LO6/vBNMwGI5mLd+38jbo1DpcBYKaWipynFETWtUR4NMAKBb/VhLslr5Xob01YNexUSQO8b7WxZuMxa6M610/GWkCMwzPIQp7UqV/46beScMPHvCQ7U8M91XR7BmY=,iv:DlnQUwuHdoTj7ZJgb43y8lH5K2eeioldrLRhZWNaVYo=,tag:ay+LCVYapXnEC4nG0o0iTA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
