apiVersion: v1
kind: Secret
metadata:
    name: wikijs-postgresql
    namespace: wikijs
type: Opaque
stringData:
    postgresql-username: ENC[AES256_GCM,data:sYROVk47,iv:rQ+0SNwn8kgVcofJUWVvwmJEpqPDiwcq+I2tBgun2hc=,tag:P+KFUpd8TSWHupvYKK7AjQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:FpyQywdK6UqDcM77DiF8r9uqLC0mVQPpI0BoQe3u,iv:UtXyBDzIdRW7Fgk+0uOYbeiflQeqmRVplF8ZiDHAMh0=,tag:RPGjjSz5ucUA51ehCRynLw==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV1Jsa0daK2dxUjA0ZUVi
            NWdlaUNKME14VHNQMVpXdHJuMVBPa0FSc3prCnZLOVhveFNXOFVNTmFMOXd2N0xt
            c3U1UTlkcG9jcThXYjdEL282bzl0WmsKLS0tIFdUa3FKNFBTN2ltMVArNi9XMjNU
            dytyWHF2R2R4SGRURFRmUHkzVXkreHMK/EM4nw0y3Lqgz24T2w2PtX9cQX9CU8FE
            GXCWxZQ/VnnhgWulcIGbAQbP4fuypgWWwqmorYc62QNv2N/3A8upeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T11:15:53Z"
    mac: ENC[AES256_GCM,data:an3Pi0B1Gn75HrMI4Xy52UWzCUE3Y2mODf2JrgdFYm+4BRiATeO+dt1ugs6OUC+ytqj6ijlRE2ljtey+WW9MFvpMp/kAaAIzquOqNj0yXkVu63aKrUcro9MUo1WDOVpyGTjigMTD+WWmASkeFH7B+I2tCFUTGmV7lq6vUowuukE=,iv:CGN+JfOmu1xwzKdeTcvHNBwdZcU4vLsPL4NUTyoTIw0=,tag:HDZTHMR7XvKxVJTTaTir4Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
