apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: matrix-secret-generator
  namespace: matrix
files:
  - secrets/matrix.secret.yaml
  - secrets/eturnal-config.secret.yaml
  - secrets/whatsapp-bridge.secret.yaml
  - secrets/meta-bridge.secret.yaml
  - secrets/gmessages-bridge.secret.yaml
