apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postmoogle-smtp
  namespace: matrix
spec:
  entryPoints:
    - smtp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postmoogle
          port: 25
