apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost-redis
  namespace: docmost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost-redis
  template:
    metadata:
      labels:
        app: docmost-redis
    spec:
      containers:
        - name: redis
          image: redis:8
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory-policy
            - noeviction
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: docmost-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: docmost-redis
  namespace: docmost
spec:
  selector:
    app: docmost-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
