apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sSbNJg7x9xppZ9HlmIM8HHNyoWpvYD1KE+pEUCkyYMY=,iv:65mcWI55W+kWGQ83zuPZ3KqE3dc+H1k95/KiBRq8bkE=,tag:bdfvsT8tfmvP8sInOV+9nA==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:SxnXA98=,iv:piL2TG9p8jKXjXw8ND6UPk/kphSpJKGu66HtNNTvjVw=,tag:JfeQyCiLvrjyT8xLS2H2lA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:2FjtVwL/DH0XryTl1/7pxR7uHtD1QaHZ,iv:W0n3FliU5RAS6e8Lymdz13aySCHPC0E6YUatKNZ/3dg=,tag:59beGlZWsioztixboHzqsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUG5vV1JHcVEyQ1I3NWpt
            R05aNUZ1eTdKemIxRmJPNDVJRGNaV2VBbVNvCkwwNnBPbHJxdVZUVkJRU2NLd3lV
            YXovMkhURXlUV0ZFZDNKazVDaUgrVVEKLS0tIDhweGlBTHE1WThaSzh1eGZqQy8z
            OWg5TmxBWlhhLzFDK2ZNeXFEWm53MlkKt0tPpYFqAILrlWhmJql9JyPebeUgsEz3
            tI2hhVL0PS71K0LWDUk69ppVn7O3zfUrvDlxIyzoAJ8NXuYxr7AMFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
    lastmodified: "2026-07-19T10:56:04Z"
    mac: ENC[AES256_GCM,data:jEHjucmKIJbct+fUvtBV+4ZU9MNonLz6QUI5nGBwkJOVG++zkSljfq9K1JWY6xoiktmyQQvOrA3u/IiyRoNtNXkyY7wvHGc1JBtUiSXuYC7lwdb1S1rGN0EkGSzv/F09XbvjBD/8Ia54otpqhOsQ7ScEnQDUJCQhGK9+h1ChRuM=,iv:N/PuwkxNl6YbDdxcK8H8T1iCaImmarLzKV+JLxo34BI=,tag:O4c7LnBXhk0icHNcguw6LA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
