// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRunData, CreateRunResponses, GetRunData, GetRunImageData, GetRunImageResponses, GetRunImageSignedUrlData, GetRunImageSignedUrlResponses, GetRunResponses, GetRunsByUserData, GetRunsByUserResponses, GetRunsData, GetRunsResponses, UploadRunImageData, UploadRunImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getRunImage = <ThrowOnError extends boolean = false>(options: Options<GetRunImageData, ThrowOnError>) => (options.client ?? client).get<GetRunImageResponses, unknown, ThrowOnError>({ url: '/api/v2/runs/{id}/image', ...options });

export const uploadRunImage = <ThrowOnError extends boolean = false>(options: Options<UploadRunImageData, ThrowOnError>) => (options.client ?? client).put<UploadRunImageResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v2/runs/{id}/image',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const getRuns = <ThrowOnError extends boolean = false>(options: Options<GetRunsData, ThrowOnError>) => (options.client ?? client).get<GetRunsResponses, unknown, ThrowOnError>({ url: '/api/v2/runs', ...options });

export const createRun = <ThrowOnError extends boolean = false>(options: Options<CreateRunData, ThrowOnError>) => (options.client ?? client).post<CreateRunResponses, unknown, ThrowOnError>({
    url: '/api/v2/runs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getRunsByUser = <ThrowOnError extends boolean = false>(options: Options<GetRunsByUserData, ThrowOnError>) => (options.client ?? client).get<GetRunsByUserResponses, unknown, ThrowOnError>({ url: '/api/v2/users/{userId}/runs', ...options });

export const getRun = <ThrowOnError extends boolean = false>(options: Options<GetRunData, ThrowOnError>) => (options.client ?? client).get<GetRunResponses, unknown, ThrowOnError>({ url: '/api/v2/runs/{id}', ...options });

export const getRunImageSignedUrl = <ThrowOnError extends boolean = false>(options: Options<GetRunImageSignedUrlData, ThrowOnError>) => (options.client ?? client).get<GetRunImageSignedUrlResponses, unknown, ThrowOnError>({ url: '/api/v2/runs/{id}/image/signed-url', ...options });
