// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type MeasurementData = {
    rate?: number;
    volume?: number;
    duration?: number;
};

export type RunView = {
    id?: string;
    user?: UserInfo;
    data?: MeasurementData;
    hasImage?: boolean;
    imageUrl?: string;
    createdAt?: string;
};

export type UserInfo = {
    id?: string;
    name?: string;
    username?: string;
};

export type CreateRunRequest = {
    userId?: string;
    duration?: number;
    rate?: number;
    volume?: number;
};

export type Pageable = {
    page?: number;
    size?: number;
    sort?: Array<string>;
};

export type PageRunView = {
    totalElements?: number;
    totalPages?: number;
    pageable?: PageableObject;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<RunView>;
    number?: number;
    sort?: SortObject;
    numberOfElements?: number;
    empty?: boolean;
};

export type PageableObject = {
    unpaged?: boolean;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    offset?: number;
    sort?: SortObject;
};

export type SortObject = {
    sorted?: boolean;
    unsorted?: boolean;
    empty?: boolean;
};

export type ImageRef = {
    key?: string;
};

export type SignedImageUrl = {
    imageRef?: ImageRef;
    url?: string;
    expiresAt?: string;
};

export type GetRunImageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}/image';
};

export type GetRunImageResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetRunImageResponse = GetRunImageResponses[keyof GetRunImageResponses];

export type UploadRunImageData = {
    body?: {
        file: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}/image';
};

export type UploadRunImageResponses = {
    /**
     * OK
     */
    200: RunView;
};

export type UploadRunImageResponse = UploadRunImageResponses[keyof UploadRunImageResponses];

export type GetRunsData = {
    body?: never;
    path?: never;
    query: {
        pageable: Pageable;
    };
    url: '/api/v2/runs';
};

export type GetRunsResponses = {
    /**
     * OK
     */
    200: PageRunView;
};

export type GetRunsResponse = GetRunsResponses[keyof GetRunsResponses];

export type CreateRunData = {
    body: CreateRunRequest;
    path?: never;
    query?: never;
    url: '/api/v2/runs';
};

export type CreateRunResponses = {
    /**
     * Created
     */
    201: RunView;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type GetRunsByUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        pageable: Pageable;
    };
    url: '/api/v2/users/{userId}/runs';
};

export type GetRunsByUserResponses = {
    /**
     * OK
     */
    200: PageRunView;
};

export type GetRunsByUserResponse = GetRunsByUserResponses[keyof GetRunsByUserResponses];

export type GetRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}';
};

export type GetRunResponses = {
    /**
     * OK
     */
    200: RunView;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type GetRunImageSignedUrlData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v2/runs/{id}/image/signed-url';
};

export type GetRunImageSignedUrlResponses = {
    /**
     * OK
     */
    200: SignedImageUrl;
};

export type GetRunImageSignedUrlResponse = GetRunImageSignedUrlResponses[keyof GetRunImageSignedUrlResponses];
