apiVersion: v1
kind: Secret
metadata:
    name: monitoring-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:oODwmpI=,iv:UudlH+fvw/YFC9RMV5u659wnmoWdp8twZXWoKAH5ni4=,tag:7643w/HZOIRC9QZq2Dd8eA==,type:str]
    admin-password: ENC[AES256_GCM,data:NdMyCqAlMYvG7gj5oLNl5kqkRjU5i8tiepAKKsFpTxI=,iv:dhjlh70SlT94Z/vtzwpyx+L2fFVfs17fqYr745xmZrY=,tag:jzw82V4PPQ0+xmR324XEnQ==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ0d1OEZLSldsTmp2bEx6
            aC81bXFMYmhjUllrQ2VRT1dEWGs3QnozbUdJCjZOMHVwVjhzK3lyUGxoM3pmbGxs
            VXpkOVJGV1FyVGVqLzhnQ0R0VTcySDAKLS0tIDljM3RUQ2I0Ukg1MVZUQmI1SE1T
            K3dYaE1KeWYySUtNdDJEclZHamUxRmcKted8AxN4j4UwRM1QIT80LbCbyH89lR6U
            QIByoyhwt8RMfPQUyab71Mkp30oSAm/D/SBUOP7w4nQD9/seFLqgIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T12:40:54Z"
    mac: ENC[AES256_GCM,data:S6ZiPhHZUnlu/q6SdWJPVa2r3sddOtPrQmlzzopFjSMyvWlApPK9XL1tge9xNFjVvRG2AYvicLL1uMafIs1xLlu96SatEUxLzOXTJ1+L6II3/UD9Nb3AirFa59kdBpT2nrEi9n8+smVg5HgBfEAUJExD5IQ8Rwo3mcJQRMgUOeA=,iv:JUhUyWQRHq+q1LuFsQRzdL9+zX/tJetz4/QR+G/aFBQ=,tag:8CQ4WpelthDCBi2pomr/Mw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
