apiVersion: v1
kind: Secret
metadata:
    name: fundus-secret
    namespace: fundus
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3Nt6myudjrC/6mBuiQGPMpKI+lKwJnkBG1/qlAPmojs=,iv:6sH1SGNd6zi+y4f0L/JFIreSAqWzlz4qJjNUJoHfyKY=,tag:9uLeXWpaoiqM1QA/rkboXQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:1a4Red4//KLDKsXQqA4jQZ52LiHcxkihzrrMnBGKRnbNBIsj1qIWYsKCX9tJB3siNHXNLRKLhlzLdAC3ewUTqZbfOO5R/PA5UMPYXzqt,iv:5ZabgRz4SPUuLCnqsXuDi902GJ5r6U8wOSojqTby32I=,tag:RzmMvkp2LlfT10J8eJixfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eTY1NERMRVExNmdzOTRn
            ajlpc1RGYzF1VCs5VTA5dnl0WnJvRnlYUVNRCm5zcW5jNEt1UjVaKzJIYnhEZXp1
            OWlUemNxc2tzQWNmTTlURlBiTkt2YkkKLS0tIERJUXVJakdkdTNtZEVuS3ZTZUJq
            alcrOVJML292SkU2MkV5V3hRODkybDQKa3nKv55jCY4sXmc1fn8SBlFLFtASSh41
            Sb0RvIEsNZkZzEgOXJPe0un3DFaAeDBV7vYsS/8FLoQPP+wCOgLgBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
    lastmodified: "2026-07-19T10:56:04Z"
    mac: ENC[AES256_GCM,data:Gqby5mPjGzMj0FpyfYHtdn0g8xOneg+3sbCO2mKA/OFhhQwProaVPY2Bx/u3FtR9Rkl9F4tPE0hCVWKqf1gWx7RxWJIdNAnZsNVKh8m0tomXakw8aki9+Fc8l8yVDG8R2wq53siwoWOHWNFtjswJmBL6oPZsN3o+WR2M9lOxzKo=,iv:bDcZNceSLSf/bvsGnkqD/oTPI8NZLCcNE4QZM8M+Hzk=,tag:3jJ2vJp6hMtKiLs3dDyXHg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
