apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secrets
    namespace: wordpress
type: Opaque
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:9EKr/uGej88KW1VvJEujA8wcdsJhcWAS3PKh5nwvlLsa3RsFYgzKTWR+pUvtv0pH0kqfFHeanREacNQNGnFsWw==,iv:vyH19LymvrvBqDkk+FGG4iV3ncyB/64XL6m/wkKg0OU=,tag:PQ0/Xov0bhbNVltb09RTMw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:OzzLjgpd3R95yUsxbBV2zwpghMDT6myPnh2owMMp+SQimokKk0O1gfVn9ijw7tL2qL6bhmrsIKcOnLdGfol1Jg==,iv:4pTR6mUeOKoE5ZooZPc3KiDmGc+A9gKq+11zLfS7uTk=,tag:2gRSOnoxmGLyFCwi0qpyVA==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Wmd0b1VMYWlRRG15Ykxy
            b3ordk9nWGhmL2tEdlNvd0JBMituRlhHVGw0Ckc4U2o0bUVYRThOeldubXNTV0c5
            K2s0bGcxV1VBWkFYUjdZb2ZjakJkcDAKLS0tIFBQbVc3YUlrSis4eE1NRUFjclR5
            QUdrbG0yWURmbFBBRlV0Yk83T0RuMjQKylIFgx5Dmi/4c0N7WSS52OKKOeGi6Ycn
            ktt8yCyKt48hdr8R199Jglap2NAf4V0h2gtQe8DIoKGCJvGDYkDhHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T09:08:57Z"
    mac: ENC[AES256_GCM,data:fDk0kmicYbf1g92/e2qZt7mVnuS9yOSI8+z8AyAJ+p/Mw8YCU+q5bavwGbVdLThtR3TsASoJRjQADpA6DGMrYXUk3OCK1OLqB4ivFKNFj5dkzmERm3GJHd7b5jCAn2ZvTMa7GzEj8FsN4yUMSY5CcYhpqJQqPC6XhplMG0qlKu8=,iv:/cWUl0gXO8GPYLCkgRVjHhrgP9jHNAVLnzsKD3alyFo=,tag:OJZqpzbEgFuJ5aNEXc2f7A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
