apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "*"
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          grafana:
            admin:
              existingSecret: monitoring-secret
              userKey: admin-user
              passwordKey: admin-password
            ingress:
              enabled: false
            sidecar:
              dashboards:
                enabled: true
                label: grafana_dashboard
                labelValue: "1"
          prometheus:
            prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              probeSelectorNilUsesHelmValues: false
              ruleSelectorNilUsesHelmValues: false
              serviceMonitorNamespaceSelector: {}
              podMonitorNamespaceSelector: {}
              probeNamespaceSelector: {}
              ruleNamespaceSelector: {}
              additionalScrapeConfigsSecret:
                name: monitoring-secret
                key: additional-scrape-configs.yaml
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      targetRevision: "*"
      helm:
        releaseName: prometheus-blackbox-exporter
        valuesObject:
          serviceMonitor:
            enabled: true
            defaults:
              labels:
                app.kubernetes.io/part-of: monitoring
          prometheusRule:
            enabled: false
    - repoURL: https://github.com/DefinitelyNotSimon13/trichter-monorepo.git
      targetRevision: HEAD
      path: deployment/overlays/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      enabled: true
      prune: true
      selfHeal: true
