apiVersion: v1
kind: Secret
metadata:
    name: umami-secret
    namespace: analytics
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:m+EEHVE=,iv:P4DD/gi/lY9bj77VFNkoiflTMm2SGnSwa5b4Tmm7cGI=,tag:z2lFuR82dxHtvKn7/mpvYA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:QcYZ5NY=,iv:8GaUGaTM3aVWIfTcFN1+g3obZZelZTuKO02UDlPFMHA=,tag:u4MNecxxN3xOi7TaW0jZQA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0ZfC8JorQrFA9Gfa3xyWW6ucSco5BU0uVW47q8usSQzydQRzOx1oTYNGkUeg5Ml/dH5MoF68VOBvoa9sFhYqtw==,iv:pgAFhW29bsfJSh/rXNWMaWlrzJ6IJsfiQmTFH0GbdNI=,tag:zyz/Lixb7rGjuOPzGSRAFA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:61KQXithE0ykUJbAjVJ6NzS//lkbO0AFDW7eJ1cVxEC/otFr31gT/CFlhrHzYw11z3Zfssf5oftdtdLioiH5FOD7spkUsLND7azlijasoDLP/CidHMzy8ITQ7HJaAb3fCL4YeoVDmX9mIFZPPOK89gmahUZohzlfpQDtTAjOUsRq2mDTmRg1ahA=,iv:Uz/4k7RhyBXnS4UFnWHwXBsYTZy2rmW8K8yMM/katTU=,tag:Hi9FkE1kt4CNBFSiKSD1EA==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:YZG7VzeDvUDA9hpAkPD2PtCzxjmKOoOPa6ybuthyjeDv8q/kPoAzt3nV/GVwb7VvQjqEZut9aRBz+tr+3LYtmw==,iv:eth91hkAzNVHp3OfTK/PJLqesye1KHur1DlZvQnX3Z4=,tag:QIDvfhaG95hlCKqMqzzBxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZmhneW0vSS8zU1RDeWtF
            NE5aUm50SWJwNHVML1dTRjh3RFMrQ1VFQ2pZClMxSUpCMGxDUkJkN0l6U1Awenh4
            KzU5amNqNm1ranlxMkVndXE1K3VMK0EKLS0tIGFYRlNFNXdoMFNEMEdzaEVvNkxX
            a1pWeTJBTDJpMUgycmhUNzlpNm0vUm8KZM8TTvjYpYiMwe034LPQ1hSs3l33dB/2
            J6+dzl5S8KcbpSjDDBHPr7ngAQotcCVdDAdFH2NK4d8qBV3srZjoag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
    lastmodified: "2026-05-09T11:02:33Z"
    mac: ENC[AES256_GCM,data:Ribi8S9/+TcHBq/f/l0D6dWzYFbTvtS2EVYNal7/TYmyhrOeM/+lXyBrylU7mc85gcHRVhCrNKJ5GcbAvKJYzTnyonzXhEMDJcQJU/xfDNe7XOzhuiHwkqMY4IO3A5z+Ux1CdWngHqkwdEguSGmAZFp5xKSF6EJzCoGtwD/jxyw=,iv:UKoAPAsEKrgCnSb52f5uUFg4noKr8k7FJEy8/+mqago=,tag:05Rf8XgsY8T/xw2yZ+2S0w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
