apiVersion: v1
kind: Service
metadata:
  name: postmoogle
  namespace: matrix
  labels:
    app.kubernetes.io/name: postmoogle
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: bridge
spec:
  selector:
    app.kubernetes.io/name: postmoogle
  ports:
    - name: smtp
      port: 25
      targetPort: 25
