apiVersion: v1
kind: ConfigMap
metadata:
    name: mautrix-whatsapp-config-template
    namespace: matrix
data:
    config.template.yaml: |
        network:
            os_name: Mautrix-WhatsApp bridge
            browser_name: unknown
            proxy: null
            get_proxy_url: null
            proxy_only_login: false
            displayname_template: '{{or .BusinessName .PushName .Phone .RedactedPhone "Unknown user"}} (WA)'
            call_start_notices: true
            identity_change_notices: false
            send_presence_on_typing: false
            enable_status_broadcast: true
            disable_status_broadcast_send: true
            mute_status_broadcast: true
            pinned_tag: m.favourite
            archive_tag:
            status_broadcast_tag: m.lowpriority
            whatsapp_thumbnail: false
            url_previews: false
            extev_polls: false
            disable_view_once: false
            force_active_delivery_receipts: false
            direct_media_auto_request: true
            initial_auto_reconnect: true
            use_whatsapp_retry_store: false
            animated_sticker:
                target: webp
                args:
                    width: 320
                    height: 320
                    fps: 25
            history_sync:
                max_initial_conversations: 15
                request_full_sync: false
                dispatch_wait: 1m
                full_sync_config:
                    days_limit: null
                    size_mb_limit: null
                    storage_quota_mb: null
                media_requests:
                    auto_request_media: true
                    request_method: immediate
                    request_local_time: 120
                    max_async_handle: 2
                backwards_on_demand: true

        bridge:
            command_prefix: '!wa'
            personal_filtering_spaces: true
            private_chat_portal_meta: true
            async_events: false
            split_portals: false
            resend_bridge_info: false
            no_bridge_info_state_key: false
            bridge_status_notices: errors
            unknown_error_auto_reconnect: null
            unknown_error_max_auto_reconnects: 10
            bridge_matrix_leave: false
            bridge_notices: false
            tag_only_on_create: true
            only_bridge_tags: [m.favourite, m.lowpriority]
            mute_only_on_create: true
            deduplicate_matrix_messages: false
            cross_room_replies: false
            revert_failed_state_changes: false
            kick_matrix_users: true
            enable_send_state_requests: false
            phone_numbers_in_profile: false
            cleanup_on_logout:
                enabled: false
                manual:
                    private: nothing
                    relayed: nothing
                    shared_no_users: nothing
                    shared_has_users: nothing
                bad_credentials:
                    private: nothing
                    relayed: nothing
                    shared_no_users: nothing
                    shared_has_users: nothing
            relay:
                enabled: true
                admin_only: true
                prefer_default: true
                allow_bridge: true
                default_relays: []
                message_formats:
                    m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
                    m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
                    m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
                    m.file: "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{ .Caption }}{{ end }}"
                    m.image: "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}: {{ .Caption }}{{ end }}"
                    m.audio: "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption }}: {{ .Caption }}{{ end }}"
                    m.video: "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}: {{ .Caption }}{{ end }}"
                    m.location: "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption }}: {{ .Caption }}{{ end }}"
                displayname_format: "{{ .DisambiguatedName }}"
            portal_create_filter:
                mode: deny
                list: []
                always_deny_from_login: []
            permissions:
                "*": relay
                "hauptspeicher.com": user
                "@simon:hauptspeicher.com": admin
            double_puppet_server_map:
                hauptspeicher.com: http://synapse.matrix.svc.cluster.local:8008

        double_puppet:
            servers: {}
            secrets:
                hauptspeicher.com: "as_token:__DOUBLEPUPPET_AS_TOKEN__"

        database:
            type: postgres
            uri: postgres://synapse:__POSTGRES_PASSWORD__@postgres.matrix.svc.cluster.local/mautrix_whatsapp?sslmode=disable
            max_open_conns: 5
            max_idle_conns: 1
            max_conn_idle_time: null
            max_conn_lifetime: null

        homeserver:
            address: http://synapse.matrix.svc.cluster.local:8008
            domain: hauptspeicher.com
            software: standard
            status_endpoint:
            message_send_checkpoint_endpoint:
            async_media: true
            websocket: false
            ping_interval_seconds: 0

        appservice:
            address: http://mautrix-whatsapp.matrix.svc.cluster.local:29318
            public_address:
            hostname: 0.0.0.0
            port: 29318
            id: whatsapp
            bot:
                username: whatsappbot
                displayname: WhatsApp Bridge
                avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
            ephemeral_events: true
            async_transactions: false
            as_token: __WA_AS_TOKEN__
            hs_token: __WA_HS_TOKEN__
            username_template: whatsapp_{{.}}

        matrix:
            message_status_events: true
            delivery_receipts: false
            message_error_notices: true
            sync_direct_chat_list: true
            federate_rooms: true
            upload_file_threshold: 5242880
            ghost_extra_profile_info: false

        provisioning:
            shared_secret: disable
            allow_matrix_auth: true
            debug_endpoints: false
            enable_session_transfers: false

        backfill:
            enabled: false
            max_initial_messages: 50
            max_catchup_messages: 500
            unread_hours_threshold: 720
            threads:
                max_initial_messages: 50
            queue:
                enabled: false
                manual: false
                batch_size: 100
                batch_delay: 20
                max_batches: -1
                max_batches_override: {}
