apiVersion: v1
kind: Service
metadata:
  name: mautrix-whatsapp
  namespace: matrix
  labels:
    app.kubernetes.io/name: mautrix-whatsapp
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: bridge
spec:
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mautrix-whatsapp
  ports:
    - name: http
      port: 29318
      targetPort: 29318
