apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: matrix
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
