apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
data:
    oidc.azure.clientSecret: ENC[AES256_GCM,data:UwtFrfNq9efveFVmio5zjH9xfGK4/Fjp5Fee2bLIo0gY7XNXvVypxwbEND0g2vCrS9oHIyXuJFI=,iv:yZaRD3B5EeUuSqz0G8xi2HqwFU02fGQoaJ0JfsewUpg=,tag:PJ2JZMP1JFStLlwUBMawsA==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZi9wWHNtY0tjRjdkR1FY
            MWhsdWtKaWJjQVFLMGdUM3FtWnRqa0ducXlJCjBobFA3ME0yVGVFN0w3b1JYbGFL
            VklVQmJJclFJSDNNS3Z0NjVsVW5OSmsKLS0tIHV1NW5VaWRkOURwVzJhZWM2bkhp
            ZkdWSDAzd2p2TmhKNlRGckZ6aUpjR1UKji+ozg+LSwelLrquDMbETVFPvZzCalD4
            vl9a6yec0rqMP2ifwKORFqp98gVcw6Wjv3aC1MuZf40BCe7a4Lln9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:59:05Z"
    mac: ENC[AES256_GCM,data:772KEODofBzsP7usoMJMYPfkaX5dHehe45W9E/6+MzA9ViGzaQVjonhNKhG4pZCGTORgp6O/9j+8PrZTNXb/Ty/gy5HwCJgkhp/j7CjkJx9BOyneR2M5LAdNu0Yd43bFSUrqktBgmiffQIa9NaMTi8JHxvth9a14lNMNnPM3ZBk=,iv:ly+YIMrbNJXP26Sk7eYSD+iYc1AZaePOcVU00l4RjOk=,tag:4nlTsV00NBvW6vtb6GNRiQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
