apiVersion: v1
kind: Secret
metadata:
    name: discord-bridge-secret
    namespace: matrix
type: Opaque
stringData:
    DISCORD_AS_TOKEN: ENC[AES256_GCM,data:TK/6bpKQaf6NVImJ9MOVqTYUfrLW/FllAZPJXFKcoDBl4L2hf6fngOsLe6OiImOuLRDc4xWBVMUt+B/e+tjkEA==,iv:3W7yAJDNeVqzR+QPp1VGqN0pMEzoXafx8YfRqbb9Vcc=,tag:z0TVmbLT5Zq046X/S3JTMQ==,type:str]
    DISCORD_HS_TOKEN: ENC[AES256_GCM,data:WehgOPCno2Z1Yl7Qd1ku0WvsOx4RFQmA1yHYG+pxfor2Doi2pS0dY7PU/qJ4mweJGB+U8Ooemq2WvN4klgLkew==,iv:MyHMXsRAyn+yaN32/w0swZjh/kAoXIJrPX2D7cVyeos=,tag:EqDbnRW+l+f0da+kO+mpEw==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRzkxWkszbUpmVUxqRUw3
            OWFuLzBvVXhyTzBYbEU5cGdkVjNXWkFMYmlnCndQVXcwR1VhVXNEWjdISXQwa2NI
            T3pCdmJvWXpBRzN5dTM5aGFZcUFGdjgKLS0tIGVYQVo5b1dXZ3NSWGkwcGt0QTdQ
            MlZjbGthRU1XR2xuVndnRVM1TWpJbnMKW0htLc5p+8Ch0b7txgZeeT9AYLDPIrhH
            /k3jo1RZfezJF5Pvem+M21bTrlcWxPJCnta+paxmyWRa+0f0NOqAJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T19:36:15Z"
    mac: ENC[AES256_GCM,data:YEWOHGyBb+SpdHG7yj9DWItOsFWeSbxjKbvJQ3gFqXP87NeLtfDYSxgxdsfrOGcqQR+A4S7lwnSNzuAWRuidNptGAfcrDxQAzR6plTP/ul1nONwqpn6pRJwcrkpCIbf3JhOL8b4SEf1Vg6jhQ9ACbqid0bubweEBORUzy8OivLU=,iv:arPsGFq1b2Ix6KjEvYoJ2hqeJG5abhwHRSs/VxcPw+Q=,tag:2UztWvt9grgiS7ev4cO59w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
