apiVersion: v1
kind: ConfigMap
metadata:
    name: eturnal-config
    namespace: matrix
data:
    eturnal.yml: ENC[AES256_GCM,data:d9lUPffpIeyjezVuOpe0YIg/GgCoN30JElSBoybchM5I8WDYRAo1qXSltXQBoJPqSEwUWo6rvno5VTAHyVhsOIFpqK/t07K/tEJfHJ6GXYgoQmoVeVnBVr7nfQ0koPBG4nqzp5OMprWlBX0xPdQqQ7oaasfcTPFSxDEmMnxWPj9YWGrnwB8NnkL2Kilv1jbKJRkjv4JDtE86ieTipoo8SvBF+178vdV7ARTltw9c187KRQ2z9+ip/D53/kysffDqzpPO7zCKuTqD6IFmW6xC+d+rn3N6TeIQHcGu88h3ALCAl8TkH2XAhik1OSYYGucvjX1I5xJOu7rRHszleB7Ge7WytGIugre4l3wn0tfpkyvdgyiGFwBBRtvyygp38ejSy/9jzs1PifYRDik2ht1qMmfZYtcR405TwdB7vQcBmHZ/Xf0YmnG6Cg6j1YN1D76A4qSljwWB/AZxWYhCcQ9cp8dR5fWeFOdGpCIWP29Cd2RZo1RDfAa3GubU6ppWjqzrZY7eZ93wbi7B9+0P0RxeLRwRA96WmItWP4E6hg==,iv:ycHVIyvRH04nir1vdLfkuSkV1a4r0SzFa9xKjAzb4/s=,tag:LfE08EkEzcUuoeH2Yo0mdg==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN01EaXlOQm92SEgycVVl
            TVhZZ1pabHZDbmRDaWhjZmphWnJJMXhNN3h3CmFrT0dxYWdkdVJ0ckRzVllZdXNn
            eGtqc1cxSXZVU1c4MjJTMkdOc1RoVVUKLS0tIFU3dmNDdm1yR2lWV3lHOVBzaGly
            N3RmKytEOHArQ3lVdGlJOC9BWDRFZGsKJ+/Woa4Y8+yNtIqqwNAOVyC74DpIXn8p
            1fpi5zde/OfoFuhXOK6uI4iIU8verJ3NULqllnRhDLAicpWn1cn+sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T12:46:44Z"
    mac: ENC[AES256_GCM,data:Kaew3qXVU75reKkw6i5gaQQl/W2gBrtJ90SON4jCbgBM9IzMKo3S5QemoSqqrwd0aGo41js8T+AZkcThb06NYMiXd0o/uM+FFlNn10KlVhY9UF+5Riekf6XN/qn+9NPwPHLQBcgE15SlVzgpUZbymnzy4g1SzA5Aa5EHEjt1dmQ=,iv:gjbXYAsYDEKJJ4SDpx3QKwoLk12Rpqqho6KusE7OjOg=,tag:VpAWTkCPAR8azui8AcoTug==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
