apiVersion: v1
kind: Secret
metadata:
    name: gmessages-bridge-secret
    namespace: matrix
type: Opaque
stringData:
    GM_AS_TOKEN: ENC[AES256_GCM,data:0LlQLPnRLhfx7PoJT3vh7a2mNtf1/0qkk7ZEs22hmjoWNmo/EBaAo5oREIFpfv3WRbgxr4DFsFr8wr5RdVem9Q==,iv:oz8ld0NHIJx0CNpqsK4vqq+pJ6PJ1HqMBw1ZSWulvdA=,tag:1Lae6FYVQEgf4Sa2W4O6mQ==,type:str]
    GM_HS_TOKEN: ENC[AES256_GCM,data:DlTKRBtzvCNYnsN2kO4FnrwX4ELUt8Hx3HxyM2kWYlWvOH6Ay3wDEVXRXDUWGVsYP9ys6DgpTqNeM1vvs/uxyA==,iv:xeI+Ax8RFIipw4bjqX3TKoVtKnkq5h6psaeqhHn8cb8=,tag:V9ywHEDcnjg1LIoK+ypqNg==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaEJYUENNK29tcGJNWmRF
            OFRNOWh2bkZMWFlTbEJHUmE2dGV3UGpML1ZrCnhjNjAxVXljekRoMEIwZmh6WU5U
            SFdINFhRMEhweHdNalhDVGk2OWNTMncKLS0tIFpMWHhLVUxTeGlPZHpuY1ZnMysy
            MFA4K1QxRWQ2dnZvVDFZWCtvNndqT1EKl9MwCQr2ruVfNbB0t4JeBD8tURowop37
            NmE2ksm4qyWUWPjNoUv1QnnaKNpuXO88M0f0mo2gjTosPTLkJdTpRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T15:50:26Z"
    mac: ENC[AES256_GCM,data:eGixXl1TrD7SxLzzJLMyI1THVWOlojYc+T5/ioicbuXInZFy1TpkeFYlaQjJpFbd5F3RYz1brtl7K3KOykLoe0IMcIHwzBNe7a5S9JOT5ZH6OFUvJqZIcDYNkER+Feis5Y2XVcc+61+OOuagFr3V8fvjvGKuegSJ6sp3jQShoGM=,iv:kNb2w08AkuMJ/vHxqmPoPkifd4Y7re3yw3lBMPn0nek=,tag:tL4XwH739RmRzdZfjva83g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
