apiVersion: v1
kind: Secret
metadata:
    name: matrix-secret
    namespace: matrix
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:SnsdHiqYxA==,iv:lBSOx8IKZrUi734hRXBQO3T8cHow2UGcEd37IroGJ+k=,tag:vf2jZIS14ei4KS4HoBFwFQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:x0gxi7ou7WI3XIWhMAY=,iv:afsQGwBg57i+yHkVhh9MMH1sQp2LiQ6/qZJySoRSUtA=,tag:oAc9a/Of87hMnTlpK9rX0A==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:h/V3ehSN9Sf4NE+EpZoVBwDZsQXAZu4vP5AoxSTZYw6yjWHHv9LUUIuV+o2oO4lOBBbwiiJyST2UxUY5z9c2UA==,iv:WiodViAMV8g8jw7PKKuH59hiFWx6HTvWZuohq7eqCUI=,tag:cYuGKZWRO7QV3TLoDWuIlQ==,type:str]
    GITHUB_OAUTH_SECRET: ENC[AES256_GCM,data:DrhqCh1BnALhZkHu/QqW9oOOvVRUklfrOJ/QWZbQ2f9xhYBTC6ZnIw==,iv:I2V8h5+4rA3i6DwNSL4dDBxwhmH093L64n6QtUFZR/8=,tag:rFy9H7rYPUL5kw7ciBtAKQ==,type:str]
    CODEBERG_OAUTH_SECRET: ENC[AES256_GCM,data:LgR5jMapDuHn/RgcTbPN4NzZf2Nwr3WRITmrYE1TmOuNPFh34Zz/WNTPErSkKPSgvXkeN0RGA4M=,iv:34E1nb8jKdjcC7G2J+ljdz+Tdfx+8cjPpolqqddLrM0=,tag:NDWBnemqVDfvbuj3YkmBKg==,type:str]
    RECAPTCHA_PRIVATE_KEY: ENC[AES256_GCM,data:KQW7sO3RSvnfX3LHKG6mn7eJmKO/EBQS2S6y7mA77blL1R9tIO0e+g==,iv:nhFHBq1HAc9TKjmtv9sDHGAVQ3mQtGibzxUPYQeK4FA=,tag:qsyvpwNXmCLqODRXFY8+sQ==,type:str]
    TURN_SHARED_SECRET: ENC[AES256_GCM,data:4HC6m0cSgZ8YUR7h3Z3hEWxPo7fZregseNPCKyDB4o/lId/YRHVsxd1NA1iu8FyPJtKEO1RXlLUYpnBnICD/Gw==,iv:uctcOQSLynfaktushQbWZsTIisQgo7sQpETjHP2oWU4=,tag:lF6+bKW471EHA7clMNg3tQ==,type:str]
    DOUBLEPUPPET_AS_TOKEN: ENC[AES256_GCM,data:77oaTHVE9gv1lm9xB+nnh1y/xdy6SHjeQqTpWYa0jynkqwRlt/RoCnG6Jgg5B1UefsGCcpfNCQqDgld5FT8EVw==,iv:E0irJMXzRh3C1TssZExiItW56NB9KlyKP2HZG41JSyI=,tag:islXF4GnZH7mbmixhNdT+g==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNzlpWFVhVzZDMFJNM3Ry
            LytWRHFFZ1pSM2pWMFNERWYxbjdJcERwNXhzCkZBQy9Bd1d3cGppdFlWN0pSMjVQ
            eUNBWG9NTWZ1eU1NaDFQVEQxaGdURnMKLS0tIFdmbitDNDdKcU5TTzZtbnJlTkFU
            TkpmYnduZXZuU1BLaWN2SWFpM3E3bDgKeXpq4l99HFRBZc2eWI6LpyyNCKQ6k6Ox
            e7OkJ4w0ON2rPnW3lCBguV9ic9Z4xAeBySJi7kP72Gj+2FTo1MjuQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T13:16:54Z"
    mac: ENC[AES256_GCM,data:0uQ4PNiPdGFW+8r+LFNFX/PZ+UGgCfK6RxTsVFnnXIFmaliZ5hifgNrJdkGg77yAfRQ+cR5CCpIVHzsN30mNR53GPl6tACTTRRzSDK9uSCPD0Pw0+9yoforD3bmpGn3Bl1iwRjRcsRepq/qEiCMVBm6sdhn1M20ZueOSsfM1JG8=,iv:9pii8b4SGvx9N3NjoW/Kt4enW6JeIdJpw5LFbvneyWM=,tag:kvYINSRrFSa3GEsP8SiHVw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
