apiVersion: v1
kind: Secret
metadata:
    name: matrix-secret
    namespace: matrix
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:1f6D42y7Gg==,iv:c6k9DTembIKtb0kvv63gJB4nmwSNRbme3ZS2Y6Guq3s=,tag:D5u3I4U5qeV4ruPK+KObpA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IwsQ4KF7qL2UX2/lR5k=,iv:YsfT7nUXbY7xso5wuURM3o2b1vDK5brXqtX9KgbWl4Q=,tag:uxlSs/rYNU3xHFOtJMMh4w==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:Acqvam+wEH5fSNLTI9CNPxLgsBZ/VWJcAKHfnhxnHdnEMzs/BXgTU6AsOohmfyE/p+nC66GJ5V1Qhi5kY2o7dg==,iv:b1dVj+txy/TATZH8KZioR7GTNwqF6YWoB9vA1qeD1jM=,tag:+HLxMoW75QzMQYjKgEb3Jg==,type:str]
    GITHUB_OAUTH_SECRET: ENC[AES256_GCM,data:eTiLXS2cimnQIx0Rn+KF8bDy1hG/h9QXa6DH95BolLArt36ZfCaMMQ==,iv:JSzbFPBCg0+lPntBg43MveSaeQ2g1WjJIOOkXH+fNbA=,tag:duTDDueD1fjyRAqRWwxLCA==,type:str]
    CODEBERG_OAUTH_SECRET: ENC[AES256_GCM,data:p8aJtSVtiSCLZuG8Ph3w+0atklqGyESYKizrDQQiCu8oHgVM6AisN33xVVtkdXanD4PxFmuAYNc=,iv:sX4FQTQEvHp4IjopHp2NansRMKmlaU4YRI5B9ifShkk=,tag:7o8P7bvLrsOR9mQX/HP5gA==,type:str]
    RECAPTCHA_PRIVATE_KEY: ENC[AES256_GCM,data:BTW+ptC6o7R8+TZzbnRf1TRLmfzCuAzZYlWuVeTqYawowN8sW5OaOQ==,iv:jIoZcYOFdrtobgkg6ynM9+ZSavs9j7YvJgNj9y7N8kA=,tag:CVkLkESsOrCYK3GmrudZWQ==,type:str]
    TURN_SHARED_SECRET: ENC[AES256_GCM,data:bWM1XRIe4At1tx6TSelhSaaFyHFbwaIG0D17TDYJ4unVQbgPmWy+IculB4WWC1OJl+Jt95107c+Ttew7ssmkBQ==,iv:aE0V9bmFQY4eLVlzpAI1/9CkK19yKkMTczSLbfVTdes=,tag:KMGAg0TwJ0jyNviCoDUDVg==,type:str]
    DOUBLEPUPPET_AS_TOKEN: ENC[AES256_GCM,data:N7Loz8ztuIvLCAMXn4PntKrP36BVK3WqIqgSHsiJlBSv/5bU0Es8VLBuwlg4i9+0NlU81jaI7T8qWbM/O0aaTA==,iv:YHhsdXVA/k6DwTlJMLWlOFmh6BuCjEJbxwEe1OekrlQ=,tag:fmSypKwvzVsRYgUiL219Gw==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZXQyY2NWYnFRZ0FidTJa
            UHdxVHl3Qml0UjZDK2E1UENZM0NqK2NlN2xrCndWR2tzdStVMXlISzZqMmdBbWRq
            ZzFYRTRPZ3UzaEVZYlE5U3hQME0xencKLS0tIFdkWGlPTkV4bm1rUWE4c2NaZjRB
            a2M1WjIzKzNpR3N5YXNha2Z6WCt1RjQKPKTJfRqRuwKvXVE4MpEVBSc9bPweOopV
            QIZHhgUymMMBpZIl9N9mznIQiNd3ijt/ZiALMCK31QA5ZPJwOmtnOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T20:49:10Z"
    mac: ENC[AES256_GCM,data:mY2kMK7Nqb8SlUYrVv/oImb52mM4UQFdjl/CvLNxQFml9WRNTy05xVGKCi4y9+zbyH+DUDwInWM+FJb+rpHw8yRQ/1vKykj+nlKX2q4+It/YTHIsQ/cfGOfZKiM3Q6qIMtjcB+CnvBlpzm9shTzqMdAT6ryMRmzbcJTmztDP3EU=,iv:C/nq1ZycFXSmEy6ko0S/YjHyrQkSpGIs1+NloomKYQk=,tag:Pfc1uSWU7GjXhu4mHxkuww==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
