apiVersion: v1
kind: Secret
metadata:
    name: meta-bridge-secret
    namespace: matrix
type: Opaque
stringData:
    META_AS_TOKEN: ENC[AES256_GCM,data:zyqbXMM7u+1PBl7egSJTZTRfXWMp72y8KWZLLd9Y/F1pAoGMLzWzuo0j6gedWuNVtJ1tb5uLAj6iBpBlKyjmeA==,iv:865WnjHj50NVlsfSPMshPoDIF+FaJfLl0yUyFH1Fe2c=,tag:h+Zwnf1m/IYB/kLdabECaA==,type:str]
    META_HS_TOKEN: ENC[AES256_GCM,data:t6X66XGKy/qFGdYbXdm8ieqFMqnPJfv2O99xp6KZW/vzaHpK0zB2lfpJaLeMJp9ClTBgSGW2K4dzE1ObEInE1Q==,iv:R4cgudHWJCn/o+nIheTo7oYkWIS+3em+TreZ2vwwK5s=,tag:muwo1qm8qc2yupLgRlu+sg==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eURXUzdQSTNrT1VEd0Jl
            d1E3Y3o5ZlhDY2ZYOEl3UldmNGQvaHprdXpVClBUaVVic3lZUUlCZnA2eitVVGxT
            REs3K0NaUzV6WTJLZStPRURFcW4rNE0KLS0tIExzdEp3eDZhcmJvbnpZekczR3hZ
            eTl5eldpUHU2eDAxWUdUUE5uaUwrWXMK/C9Q9aWe7nE1lFliakoS5/KMdPgi6hCr
            TAXY7RP8Srao9wKqfTF2uXqgHsVytxklQ3US8f66a0+H56Fyw1cLdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T15:50:26Z"
    mac: ENC[AES256_GCM,data:YbgUQLsVO5o+Dc7S6+lUYH0vGHqJYi2J2U74QgdF3fpp4RGmwlKDQiOXZPAjp+L+c6SPDrEEcU89ulAIAPTZmosoy5QaOrEjGRylwma06Lyyl80ZwsaOFUVAHwpcI9qS3EH8ThLTHqZib/xS4gj45YOmOPgmT1NoQLIN4X4vHuI=,iv:9qLMICHIO9ZjF7P30HXMmVYRl7+2Gn+PQWQ4t8JQJ1U=,tag:4Y1mkqYH9Rc16hV7MIGbeA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
