apiVersion: v1
kind: Secret
metadata:
    name: postmoogle-secret
    namespace: matrix
stringData:
    POSTMOOGLE_LOGIN: ENC[AES256_GCM,data:XvkqC0Q2F/36og==,iv:RVPK3QW03cMlh1v6k37MjRNgVN03AudhSjN1DShtbcQ=,tag:19sfIEYh4rEzlQDRt5ylKA==,type:str]
    POSTMOOGLE_PASSWORD: ENC[AES256_GCM,data:q3J9MrQUgh9vRFc+Bh/7+YRDHcEI2InW,iv:XRkPZM9lCBrqvVIP2i9aO30SjaivKoxvJO3K7Sbv5SE=,tag:mOvdo0S35WYHSv33VF9gIw==,type:str]
    POSTMOOGLE_DATA_SECRET: ENC[AES256_GCM,data:Qlsopstp2k+K5hC2h3/NTYsZC52izmGNc+WTHZ8QQoU=,iv:L86tuPpJfO9rZiqxqupR4sDbeZHAZOGFpBEyItj4Reo=,tag:Ae8hbfbMESidfXBuERpl3w==,type:str]
    POSTMOOGLE_DB_DSN: ENC[AES256_GCM,data:hqDMtYq7ZEytIdAqw7LW2lvlgAp5L3icf/TSdIRzfZ3q/Mnx14aVjzoR0cg3J1N+kOQgQJvQRTBMuwFnNl8dn20eOdVKRIkkpHSsPBcpAExcAasnYnyno9OZMJzEZA==,iv:CsbddxdjeeyS3LA1vvJb50V/B9yd9SgQMV0m00+nOss=,tag:dnh9Z37PWGa/bTrbIeA4gQ==,type:str]
    POSTMOOGLE_RELAY_USERNAME: ENC[AES256_GCM,data:7HLGTDM5ag==,iv:zl4WSt6DXPBbzI5EydN8BTaq5tRM2K4NorX9mct+jI8=,tag:rU8H64qDdSCAlusLp2kN9g==,type:str]
    POSTMOOGLE_RELAY_PASSWORD: ENC[AES256_GCM,data:Bf1h8etWcwYuF/3KMUmJ6y4gDIlow96ZZo/heBfe4vGlxA2HG5aLVg==,iv:PwvDogpMmOPDtJLV9ss0t9w/nFQLq3bwmtkjdn9Odqo=,tag:JgOkrhZ8WewfQLnfL3CPPw==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSE1xS3NIWDVxcXVERnl1
            WGhyTjZFSW85Znd1a1N6M1c4OGRQUEkxczJ3CldocEdWbVNNZ3M5U1FVZVRXajVI
            S0RPcFJBaGIraEYrWmFySVUxK3pnczgKLS0tIHd1aVZHMXRVR1BjUnlFZ1F2TUoy
            dk9NbjMyT0hKcGQ5aXZ3QkR3VXVLZUEKaL+atULAqyRoTTebNbTsKGPieRG+3iFx
            OGlel/Lr3G+9ImEnT270ltj77r2zpSLCv+ZDLJ13DGxoLPgUS5THjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T19:09:20Z"
    mac: ENC[AES256_GCM,data:Oe45v14G7F6Z0OSDur5lPh8wKcqs7WIUa4svWGYSZTzrl9DJqqMX38yawwloUPwqj8iFMCMoKrKcJkYN+dbRqdVlMPAtiWl3H3IJNKcAwF2OFezKWAysIAtwJ23HGpdChyrxhKk8OTooAo7pIyoWbW7NAaBEiBoPs7z2LML2WBw=,iv:cOxYHR6RtwqpTRQ4tduw94OUOZ01X7w1PjXa1BQlVVY=,tag:5qqVn7l4e3PSrUSq91e9dA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
