apiVersion: v1
kind: Secret
metadata:
    name: postmoogle-secret
    namespace: matrix
stringData:
    POSTMOOGLE_LOGIN: ENC[AES256_GCM,data:k4DWHQTg3+mBnA==,iv:ToObtQoxV6GpB7mlvsMTRPhGeHxv4JVNzO0lLZArp3g=,tag:vicVGoku76ZG3g/ad+ooMQ==,type:str]
    POSTMOOGLE_PASSWORD: ENC[AES256_GCM,data:Q3q3q6ugNibFDREzvKJFwypLqHOUcTk6,iv:89motC2fQfpSMccYI2sZqTh+lYiWN3UwvKO5P0GH/g8=,tag:IwlnZpKGZQ+bKih4Mzg1hw==,type:str]
    POSTMOOGLE_DATA_SECRET: ENC[AES256_GCM,data:j55FUikhFoQNCaZcgfFVI5RNZmWBiaVNRwZkJxlezhs=,iv:EjuhLaeTWga1IJkh1ipv7EsvEu6uoBLLbpwHhPG8T5M=,tag:b5cp4jpE6xcmMmuFQilC3g==,type:str]
    POSTMOOGLE_DB_DSN: ENC[AES256_GCM,data:ONtQ/4AYyjeHFpd+76FcHHB7f0WswzSTtI0xAcqNx1VahyHzgRmUb3QnaB74pOQcc+fbllParIBqQLP8v0Bu5mhEfmBWgsE6mXMWdy/broqbipn6cWkWRfssosjXBg==,iv:7Sr1N5ZWNgWOs4npVsvj+BVU6vmqNx8eVnq3Oed40C8=,tag:NOJFIsQ70HH3nyMXs+1DWg==,type:str]
    POSTMOOGLE_RELAY_USERNAME: ENC[AES256_GCM,data:wbGZA1InHA==,iv:pPDQmlMrUymsaJLm4fPSrgvPUSxU9gbBsNk40tfPHm4=,tag:u9CcgHpNakcixCqJlnC39A==,type:str]
    POSTMOOGLE_RELAY_PASSWORD: ENC[AES256_GCM,data:du1Mn75X07yC1jxeEzRAdaBkRgU4x8lUhCedh249iIeshM/+R+fNdg==,iv:GkOTLu9UKNrX8jOEP3XuFL0DlR1PIVx0HIgRN2AZseQ=,tag:s3nYQr/pSNa/CGN3/tuP3g==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VkxSV1FGOTNoV0E0ODJX
            MnYwd1FyQkd3bkFxYUtkbElHM0tBTC9RK3pBCjU3a3l1bE8yaXR3U1grOWNqTXV1
            YnlDa1lITmJ2TitpQ2tzd1FqNW1aa0kKLS0tIHY3WmFSNjJjOG9XOU1BYVJTRkZq
            b2w2L3U4R1lGMTVzK0h5LzBmVkVBTncK6w8BJgENp0PNs+qc/riinVb1DgfyzoVw
            j33Yr5Dc4jP/M/C6mdObRRzP95jHqpZCkeX7BkrFnh6GCUVyn9PAKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T13:16:54Z"
    mac: ENC[AES256_GCM,data:cb1URT3HV1e3P5Q4rd8cDUDckfpJz4Xs3CJa5X0GVWFRmkMHI6ADXj8FWzAiFb7n9Yh82qpMCm2HZW5Gxiot3cPR+LSfz3hO+dMn9+xm9DmKX3Sffo7mjH0t7+aCvJpT7MKnzYrX9EpsehT0OHgENOI/barXGFD+idrsntiZeS0=,iv:wA71HxHYDo4w+vO4DsI8SRmOff7m96Zw/PPqsoR0MTk=,tag:LpWSYg6jq1RnOEDGwjzBNw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
