apiVersion: v1
kind: Secret
metadata:
    name: whatsapp-bridge-secret
    namespace: matrix
type: Opaque
stringData:
    WA_AS_TOKEN: ENC[AES256_GCM,data:v739olnkDY045cwxRupnydxEh+PAtCUPQ9T4bwD/nm+UpAnadjpIle8PotM=,iv:ytBdwqpwhPyFDQ3aywPO2ukXlh8J/ec2rm5zFvedxSk=,tag:TfVyXjqiP5id10NlHiZR9A==,type:str]
    WA_HS_TOKEN: ENC[AES256_GCM,data:Uoqu7p67XtAtQUf005nCoyYpDgPn5b5dFfjCiMjuTFYpM2kmfbny4miPhQA=,iv:sFaf5mUq5yRy7HbCX5pldxRJvVC4B1keUBl1Qs992Ks=,tag:Bx5GxcWtSJc9NucZ+gUvMg==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MWJybzRldXlDTll0WnF1
            QTJkVC9aWGhzWjVzeW5kOFlhVnZQaHlIa0RNCjcyd1R5Z0t6Qk1SMy9iY3lFNXpo
            L0c0KzRGWTNiUzk3V1owUEpuUjNJaFUKLS0tIEVnajRmdjluU3draktOUkNJUFc3
            elg4QmNHaUt1SStpODNRZDZUbzlUbjQKyKPHgUPpVmasWIVSbXal50A72teirAR+
            h2g1MRG0fQlLjsqsUGqZqPKWOU7Vtuk+ITcfIL656iwjOPaiKPPQaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:06:05Z"
    mac: ENC[AES256_GCM,data:b5KgLQoLxQaFsw8MQcDE0G6/ETSzzVaLQnOw6o6xc14KzCvRStpBhAPqBINzXKz2H/c9EChPS/DWFrGbUxh0wT1ZdcCEBmX68qrL3IlwLORgwo3Zp6kYhGou7d4PEB7ECCVJtIIGPTjRD9qqp+MWk8pnbDjEJBt4lebECiBm89c=,iv:LwFQiIWqMstg29nSyBO46ft1vAbyG1B3N5KDiDQu2A0=,tag:PPtW8+dNKbippKAQsnauFA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
