apiVersion: v1
kind: Secret
metadata:
    name: docmost-secret
    namespace: docmost
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:+v7nqxjyEEO7Z1IJqnWpeurV0/i9kRH0VXQQZbqpnUvUGUcMHmX40gWe09GwikA3MyCGwkbub6QR1CPjiwLRXw==,iv:GJopR8C6OggKgAF0ktQvUHMfQDB2Xsk/HzY8QJVi7E8=,tag:gjFAEk7/tlIQXTOs4eW8tw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:u+6Wp7CpwD842h7ePfbTBIgqWOzdCzf0ZoBXdIJu08B+OrzZq+AQ8wH1H8E0qOtjmfGuIhcAuWKzk34+CcUfKQ==,iv:/mf/XCIcfhKpBS6wnYWc4UxuCuobocfwqiXeSy8+bso=,tag:kHU1bSX/EebzNbiRCdK2Eg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:xZJLQBWRtuS7SwfTR0nneyypyAd02zJi/TURC8xEGz8jPzdQIDKE+QPoSymaMndNOmYiKMH7t9IKqIFiucjnjmbFmTxReD94ZXg80QQVNaiViShGozLR7Noy38N3RXwHdRhNUjI9fR+k3LtdWPyATAScrw==,iv:KznYuTpSOrx0s/HqV5Iu5fp77acrZBwfPDwUq3pHI3Q=,tag:m9LDWZ1fO3XoFlpemYgAMQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:UGTmAdaB3g==,iv:Q0fL0MTG8WuC7tuKEmgozIRc8CO5AuVlaavjKkunxfs=,tag:t1ErI64+E9RRjbHlPiWYLg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:LRPw10KZjJ32xdT7ZF3vPhW6hGLo8Lam85CkpIJE4nkub4PmQ80hwg==,iv:zFrENdVNJ04/yVGEV5p9Mg+8hCo7SXDIFIDEkk+DIuw=,tag:OXmxfGUjL09IjDKIZMOJ0w==,type:str]
sops:
    age:
        - recipient: age1msqyt8em4a4hvjftcfu0lx8j0clfpkf8wstqhlsqdp2efhujjf0sh2c4hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UktTL01EMmxvZ3JSNHM4
            a2xUTFEyTStPSlQ0UHNDNFJpSVJQcFR4TERzCnFrZ2J6b09Ec0dtYThBNGhWZy9S
            RlR6RElCNU0waUt6U2plUncwUnZOYWMKLS0tICt2WkZINkpxOGJ5MGdqdlZQbFZW
            d05BbExyYU5YOWFjR1V5NFlHbGFQeG8K6OPBlXDB31V0PeD7xiFEyj2S2WwXCLTL
            EHRLe3aYYSV+ArTn0SPoithV9EwQ1hMOetg3G8OV4LkxEK4k4zN2fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T13:15:55Z"
    mac: ENC[AES256_GCM,data:xELqrFwEmlX40cYTSdqz3wW5EKu8kfWEoJ1o2/jQC2Jos7fM20zy2rpH/IyHaboi+H++7TrJSMfCz3hkYFW46HTkenUzB+k6YzFraV6Y2jjmeRu/TMtTL7/xa1jVdKfCXuE34jmsf7yf2JhW29UMdyI95tbPPTn+1kpQlgG11do=,iv:5tEgxOj4rzurdeEyhNk9E67Cqj+z/kVVdeEVEByCaZ8=,tag:NxPpuATAnI2P9kKRXl65rg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
