/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AppRouteImport } from './routes/{-$locale}/app'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as Char123LocaleChar125AppIndexRouteImport } from './routes/{-$locale}/app/index'
import { Route as Char123LocaleChar125AppLeaderboardRouteImport } from './routes/{-$locale}/app/leaderboard'
import { Route as Char123LocaleChar125AppFeedRouteImport } from './routes/{-$locale}/app/feed'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppRoute = Char123LocaleChar125AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AppIndexRoute =
  Char123LocaleChar125AppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125AppLeaderboardRoute =
  Char123LocaleChar125AppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125AppFeedRoute =
  Char123LocaleChar125AppFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/about': typeof AboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/{-$locale}/app/feed': typeof Char123LocaleChar125AppFeedRoute
  '/{-$locale}/app/leaderboard': typeof Char123LocaleChar125AppLeaderboardRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/{-$locale}/app/feed': typeof Char123LocaleChar125AppFeedRoute
  '/{-$locale}/app/leaderboard': typeof Char123LocaleChar125AppLeaderboardRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/about': typeof AboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/{-$locale}/app/feed': typeof Char123LocaleChar125AppFeedRoute
  '/{-$locale}/app/leaderboard': typeof Char123LocaleChar125AppLeaderboardRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/about'
    | '/demo/better-auth'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/{-$locale}/app'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/{-$locale}/app/feed'
    | '/{-$locale}/app/leaderboard'
    | '/{-$locale}/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/demo/better-auth'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/{-$locale}'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/{-$locale}/app/feed'
    | '/{-$locale}/app/leaderboard'
    | '/{-$locale}/app'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/about'
    | '/demo/better-auth'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/{-$locale}/app'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/{-$locale}/app/feed'
    | '/{-$locale}/app/leaderboard'
    | '/{-$locale}/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app': {
      id: '/{-$locale}/app'
      path: '/app'
      fullPath: '/{-$locale}/app'
      preLoaderRoute: typeof Char123LocaleChar125AppRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/app/': {
      id: '/{-$locale}/app/'
      path: '/'
      fullPath: '/{-$locale}/app/'
      preLoaderRoute: typeof Char123LocaleChar125AppIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/app/leaderboard': {
      id: '/{-$locale}/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/{-$locale}/app/leaderboard'
      preLoaderRoute: typeof Char123LocaleChar125AppLeaderboardRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/app/feed': {
      id: '/{-$locale}/app/feed'
      path: '/feed'
      fullPath: '/{-$locale}/app/feed'
      preLoaderRoute: typeof Char123LocaleChar125AppFeedRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125AppRouteChildren {
  Char123LocaleChar125AppFeedRoute: typeof Char123LocaleChar125AppFeedRoute
  Char123LocaleChar125AppLeaderboardRoute: typeof Char123LocaleChar125AppLeaderboardRoute
  Char123LocaleChar125AppIndexRoute: typeof Char123LocaleChar125AppIndexRoute
}

const Char123LocaleChar125AppRouteChildren: Char123LocaleChar125AppRouteChildren =
  {
    Char123LocaleChar125AppFeedRoute: Char123LocaleChar125AppFeedRoute,
    Char123LocaleChar125AppLeaderboardRoute:
      Char123LocaleChar125AppLeaderboardRoute,
    Char123LocaleChar125AppIndexRoute: Char123LocaleChar125AppIndexRoute,
  }

const Char123LocaleChar125AppRouteWithChildren =
  Char123LocaleChar125AppRoute._addFileChildren(
    Char123LocaleChar125AppRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AppRoute: typeof Char123LocaleChar125AppRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AppRoute: Char123LocaleChar125AppRouteWithChildren,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
