/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125AppRouteImport } from './routes/{-$locale}/app'
import { Route as DePrivacyRouteImport } from './routes/de.privacy'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known/assetlinks[.]json'
import { Route as Char123LocaleChar125PublicRouteRouteImport } from './routes/{-$locale}/_public/route'
import { Route as Char123LocaleChar125AppIndexRouteImport } from './routes/{-$locale}/app/index'
import { Route as Char123LocaleChar125PublicIndexRouteImport } from './routes/{-$locale}/_public/index'
import { Route as Char123LocaleChar125OauthLoginRouteImport } from './routes/{-$locale}/oauth/login'
import { Route as Char123LocaleChar125AppSettingsRouteImport } from './routes/{-$locale}/app/settings'
import { Route as Char123LocaleChar125AppLeaderboardRouteImport } from './routes/{-$locale}/app/leaderboard'
import { Route as Char123LocaleChar125AppFeedRouteImport } from './routes/{-$locale}/app/feed'
import { Route as Char123LocaleChar125AppAdminRouteImport } from './routes/{-$locale}/app/admin'
import { Route as Char123LocaleChar125PublicNewMobileRouteImport } from './routes/{-$locale}/_public/new-mobile'
import { Route as Char123LocaleChar125PublicMobileRouteImport } from './routes/{-$locale}/_public/mobile'
import { Route as Char123LocaleChar125PublicGoodbyeRouteImport } from './routes/{-$locale}/_public/goodbye'
import { Route as Char123LocaleChar125PublicAboutRouteImport } from './routes/{-$locale}/_public/about'
import { Route as Char123LocaleChar125AuthVerifyOtpRouteImport } from './routes/{-$locale}/_auth/verify-otp'
import { Route as Char123LocaleChar125AuthSignupRouteImport } from './routes/{-$locale}/_auth/signup'
import { Route as Char123LocaleChar125AuthResetPasswordRouteImport } from './routes/{-$locale}/_auth/reset-password'
import { Route as Char123LocaleChar125AuthLoginRouteImport } from './routes/{-$locale}/_auth/login'
import { Route as Char123LocaleChar125AuthForgotPasswordRouteImport } from './routes/{-$locale}/_auth/forgot-password'
import { Route as Char123LocaleChar125AuthConsentRouteImport } from './routes/{-$locale}/_auth/consent'
import { Route as Char123LocaleChar125AuthCompleteProfileRouteImport } from './routes/{-$locale}/_auth/complete-profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as Char123LocaleChar125AppAdminIndexRouteImport } from './routes/{-$locale}/app/admin/index'
import { Route as Char123LocaleChar125AppProfileChar123UserIdChar125RouteImport } from './routes/{-$locale}/app/profile.{-$userId}'
import { Route as Char123LocaleChar125AppAdminUsersRouteImport } from './routes/{-$locale}/app/admin/users'
import { Route as Char123LocaleChar125AppAdminRunsRouteImport } from './routes/{-$locale}/app/admin/runs'
import { Route as Char123LocaleChar125PublicPolicyPrivacyRouteImport } from './routes/{-$locale}/_public/policy/privacy'
import { Route as Char123LocaleChar125PublicPolicyImprintRouteImport } from './routes/{-$locale}/_public/policy/imprint'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known/oauth-authorization-server.api.auth'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AppRoute = Char123LocaleChar125AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const DePrivacyRoute = DePrivacyRouteImport.update({
  id: '/de/privacy',
  path: '/de/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PublicRouteRoute =
  Char123LocaleChar125PublicRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppIndexRoute =
  Char123LocaleChar125AppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125PublicIndexRoute =
  Char123LocaleChar125PublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125OauthLoginRoute =
  Char123LocaleChar125OauthLoginRouteImport.update({
    id: '/oauth/login',
    path: '/oauth/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppSettingsRoute =
  Char123LocaleChar125AppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125AppLeaderboardRoute =
  Char123LocaleChar125AppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125AppFeedRoute =
  Char123LocaleChar125AppFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125AppAdminRoute =
  Char123LocaleChar125AppAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125PublicNewMobileRoute =
  Char123LocaleChar125PublicNewMobileRouteImport.update({
    id: '/new-mobile',
    path: '/new-mobile',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicMobileRoute =
  Char123LocaleChar125PublicMobileRouteImport.update({
    id: '/mobile',
    path: '/mobile',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicGoodbyeRoute =
  Char123LocaleChar125PublicGoodbyeRouteImport.update({
    id: '/goodbye',
    path: '/goodbye',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicAboutRoute =
  Char123LocaleChar125PublicAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125AuthVerifyOtpRoute =
  Char123LocaleChar125AuthVerifyOtpRouteImport.update({
    id: '/_auth/verify-otp',
    path: '/verify-otp',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthSignupRoute =
  Char123LocaleChar125AuthSignupRouteImport.update({
    id: '/_auth/signup',
    path: '/signup',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthResetPasswordRoute =
  Char123LocaleChar125AuthResetPasswordRouteImport.update({
    id: '/_auth/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthLoginRoute =
  Char123LocaleChar125AuthLoginRouteImport.update({
    id: '/_auth/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthForgotPasswordRoute =
  Char123LocaleChar125AuthForgotPasswordRouteImport.update({
    id: '/_auth/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthConsentRoute =
  Char123LocaleChar125AuthConsentRouteImport.update({
    id: '/_auth/consent',
    path: '/consent',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthCompleteProfileRoute =
  Char123LocaleChar125AuthCompleteProfileRouteImport.update({
    id: '/_auth/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AppAdminIndexRoute =
  Char123LocaleChar125AppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AppAdminRoute,
  } as any)
const Char123LocaleChar125AppProfileChar123UserIdChar125Route =
  Char123LocaleChar125AppProfileChar123UserIdChar125RouteImport.update({
    id: '/profile/{-$userId}',
    path: '/profile/{-$userId}',
    getParentRoute: () => Char123LocaleChar125AppRoute,
  } as any)
const Char123LocaleChar125AppAdminUsersRoute =
  Char123LocaleChar125AppAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125AppAdminRoute,
  } as any)
const Char123LocaleChar125AppAdminRunsRoute =
  Char123LocaleChar125AppAdminRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => Char123LocaleChar125AppAdminRoute,
  } as any)
const Char123LocaleChar125PublicPolicyPrivacyRoute =
  Char123LocaleChar125PublicPolicyPrivacyRouteImport.update({
    id: '/policy/privacy',
    path: '/policy/privacy',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicPolicyImprintRoute =
  Char123LocaleChar125PublicPolicyImprintRouteImport.update({
    id: '/policy/imprint',
    path: '/policy/imprint',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/.well-known/oauth-authorization-server/api/auth',
    path: '/.well-known/oauth-authorization-server/api/auth',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125PublicRouteRouteWithChildren
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/de/privacy': typeof DePrivacyRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/complete-profile': typeof Char123LocaleChar125AuthCompleteProfileRoute
  '/{-$locale}/consent': typeof Char123LocaleChar125AuthConsentRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/verify-otp': typeof Char123LocaleChar125AuthVerifyOtpRoute
  '/{-$locale}/about': typeof Char123LocaleChar125PublicAboutRoute
  '/{-$locale}/goodbye': typeof Char123LocaleChar125PublicGoodbyeRoute
  '/{-$locale}/mobile': typeof Char123LocaleChar125PublicMobileRoute
  '/{-$locale}/new-mobile': typeof Char123LocaleChar125PublicNewMobileRoute
  '/{-$locale}/app/admin': typeof Char123LocaleChar125AppAdminRouteWithChildren
  '/{-$locale}/app/feed': typeof Char123LocaleChar125AppFeedRoute
  '/{-$locale}/app/leaderboard': typeof Char123LocaleChar125AppLeaderboardRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125AppSettingsRoute
  '/{-$locale}/oauth/login': typeof Char123LocaleChar125OauthLoginRoute
  '/{-$locale}/': typeof Char123LocaleChar125PublicIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/{-$locale}/policy/imprint': typeof Char123LocaleChar125PublicPolicyImprintRoute
  '/{-$locale}/policy/privacy': typeof Char123LocaleChar125PublicPolicyPrivacyRoute
  '/{-$locale}/app/admin/runs': typeof Char123LocaleChar125AppAdminRunsRoute
  '/{-$locale}/app/admin/users': typeof Char123LocaleChar125AppAdminUsersRoute
  '/{-$locale}/app/profile/{-$userId}': typeof Char123LocaleChar125AppProfileChar123UserIdChar125Route
  '/{-$locale}/app/admin/': typeof Char123LocaleChar125AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125PublicIndexRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/de/privacy': typeof DePrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/complete-profile': typeof Char123LocaleChar125AuthCompleteProfileRoute
  '/{-$locale}/consent': typeof Char123LocaleChar125AuthConsentRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/verify-otp': typeof Char123LocaleChar125AuthVerifyOtpRoute
  '/{-$locale}/about': typeof Char123LocaleChar125PublicAboutRoute
  '/{-$locale}/goodbye': typeof Char123LocaleChar125PublicGoodbyeRoute
  '/{-$locale}/mobile': typeof Char123LocaleChar125PublicMobileRoute
  '/{-$locale}/new-mobile': typeof Char123LocaleChar125PublicNewMobileRoute
  '/{-$locale}/app/feed': typeof Char123LocaleChar125AppFeedRoute
  '/{-$locale}/app/leaderboard': typeof Char123LocaleChar125AppLeaderboardRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125AppSettingsRoute
  '/{-$locale}/oauth/login': typeof Char123LocaleChar125OauthLoginRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/{-$locale}/policy/imprint': typeof Char123LocaleChar125PublicPolicyImprintRoute
  '/{-$locale}/policy/privacy': typeof Char123LocaleChar125PublicPolicyPrivacyRoute
  '/{-$locale}/app/admin/runs': typeof Char123LocaleChar125AppAdminRunsRoute
  '/{-$locale}/app/admin/users': typeof Char123LocaleChar125AppAdminUsersRoute
  '/{-$locale}/app/profile/{-$userId}': typeof Char123LocaleChar125AppProfileChar123UserIdChar125Route
  '/{-$locale}/app/admin': typeof Char123LocaleChar125AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/_public': typeof Char123LocaleChar125PublicRouteRouteWithChildren
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/de/privacy': typeof DePrivacyRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/_auth/complete-profile': typeof Char123LocaleChar125AuthCompleteProfileRoute
  '/{-$locale}/_auth/consent': typeof Char123LocaleChar125AuthConsentRoute
  '/{-$locale}/_auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordRoute
  '/{-$locale}/_auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/_auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordRoute
  '/{-$locale}/_auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/_auth/verify-otp': typeof Char123LocaleChar125AuthVerifyOtpRoute
  '/{-$locale}/_public/about': typeof Char123LocaleChar125PublicAboutRoute
  '/{-$locale}/_public/goodbye': typeof Char123LocaleChar125PublicGoodbyeRoute
  '/{-$locale}/_public/mobile': typeof Char123LocaleChar125PublicMobileRoute
  '/{-$locale}/_public/new-mobile': typeof Char123LocaleChar125PublicNewMobileRoute
  '/{-$locale}/app/admin': typeof Char123LocaleChar125AppAdminRouteWithChildren
  '/{-$locale}/app/feed': typeof Char123LocaleChar125AppFeedRoute
  '/{-$locale}/app/leaderboard': typeof Char123LocaleChar125AppLeaderboardRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125AppSettingsRoute
  '/{-$locale}/oauth/login': typeof Char123LocaleChar125OauthLoginRoute
  '/{-$locale}/_public/': typeof Char123LocaleChar125PublicIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/{-$locale}/_public/policy/imprint': typeof Char123LocaleChar125PublicPolicyImprintRoute
  '/{-$locale}/_public/policy/privacy': typeof Char123LocaleChar125PublicPolicyPrivacyRoute
  '/{-$locale}/app/admin/runs': typeof Char123LocaleChar125AppAdminRunsRoute
  '/{-$locale}/app/admin/users': typeof Char123LocaleChar125AppAdminUsersRoute
  '/{-$locale}/app/profile/{-$userId}': typeof Char123LocaleChar125AppProfileChar123UserIdChar125Route
  '/{-$locale}/app/admin/': typeof Char123LocaleChar125AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/.well-known/assetlinks.json'
    | '/.well-known/openid-configuration'
    | '/de/privacy'
    | '/{-$locale}/app'
    | '/api/auth/$'
    | '/{-$locale}/complete-profile'
    | '/{-$locale}/consent'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/signup'
    | '/{-$locale}/verify-otp'
    | '/{-$locale}/about'
    | '/{-$locale}/goodbye'
    | '/{-$locale}/mobile'
    | '/{-$locale}/new-mobile'
    | '/{-$locale}/app/admin'
    | '/{-$locale}/app/feed'
    | '/{-$locale}/app/leaderboard'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/oauth/login'
    | '/{-$locale}/'
    | '/{-$locale}/app/'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/{-$locale}/policy/imprint'
    | '/{-$locale}/policy/privacy'
    | '/{-$locale}/app/admin/runs'
    | '/{-$locale}/app/admin/users'
    | '/{-$locale}/app/profile/{-$userId}'
    | '/{-$locale}/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/.well-known/assetlinks.json'
    | '/.well-known/openid-configuration'
    | '/de/privacy'
    | '/api/auth/$'
    | '/{-$locale}/complete-profile'
    | '/{-$locale}/consent'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/signup'
    | '/{-$locale}/verify-otp'
    | '/{-$locale}/about'
    | '/{-$locale}/goodbye'
    | '/{-$locale}/mobile'
    | '/{-$locale}/new-mobile'
    | '/{-$locale}/app/feed'
    | '/{-$locale}/app/leaderboard'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/oauth/login'
    | '/{-$locale}/app'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/{-$locale}/policy/imprint'
    | '/{-$locale}/policy/privacy'
    | '/{-$locale}/app/admin/runs'
    | '/{-$locale}/app/admin/users'
    | '/{-$locale}/app/profile/{-$userId}'
    | '/{-$locale}/app/admin'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/_public'
    | '/.well-known/assetlinks.json'
    | '/.well-known/openid-configuration'
    | '/de/privacy'
    | '/{-$locale}/app'
    | '/api/auth/$'
    | '/{-$locale}/_auth/complete-profile'
    | '/{-$locale}/_auth/consent'
    | '/{-$locale}/_auth/forgot-password'
    | '/{-$locale}/_auth/login'
    | '/{-$locale}/_auth/reset-password'
    | '/{-$locale}/_auth/signup'
    | '/{-$locale}/_auth/verify-otp'
    | '/{-$locale}/_public/about'
    | '/{-$locale}/_public/goodbye'
    | '/{-$locale}/_public/mobile'
    | '/{-$locale}/_public/new-mobile'
    | '/{-$locale}/app/admin'
    | '/{-$locale}/app/feed'
    | '/{-$locale}/app/leaderboard'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/oauth/login'
    | '/{-$locale}/_public/'
    | '/{-$locale}/app/'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/{-$locale}/_public/policy/imprint'
    | '/{-$locale}/_public/policy/privacy'
    | '/{-$locale}/app/admin/runs'
    | '/{-$locale}/app/admin/users'
    | '/{-$locale}/app/profile/{-$userId}'
    | '/{-$locale}/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  DePrivacyRoute: typeof DePrivacyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/app': {
      id: '/{-$locale}/app'
      path: '/app'
      fullPath: '/{-$locale}/app'
      preLoaderRoute: typeof Char123LocaleChar125AppRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/de/privacy': {
      id: '/de/privacy'
      path: '/de/privacy'
      fullPath: '/de/privacy'
      preLoaderRoute: typeof DePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_public': {
      id: '/{-$locale}/_public'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125PublicRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/': {
      id: '/{-$locale}/app/'
      path: '/'
      fullPath: '/{-$locale}/app/'
      preLoaderRoute: typeof Char123LocaleChar125AppIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/_public/': {
      id: '/{-$locale}/_public/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125PublicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/oauth/login': {
      id: '/{-$locale}/oauth/login'
      path: '/oauth/login'
      fullPath: '/{-$locale}/oauth/login'
      preLoaderRoute: typeof Char123LocaleChar125OauthLoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/settings': {
      id: '/{-$locale}/app/settings'
      path: '/settings'
      fullPath: '/{-$locale}/app/settings'
      preLoaderRoute: typeof Char123LocaleChar125AppSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/app/leaderboard': {
      id: '/{-$locale}/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/{-$locale}/app/leaderboard'
      preLoaderRoute: typeof Char123LocaleChar125AppLeaderboardRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/app/feed': {
      id: '/{-$locale}/app/feed'
      path: '/feed'
      fullPath: '/{-$locale}/app/feed'
      preLoaderRoute: typeof Char123LocaleChar125AppFeedRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/app/admin': {
      id: '/{-$locale}/app/admin'
      path: '/admin'
      fullPath: '/{-$locale}/app/admin'
      preLoaderRoute: typeof Char123LocaleChar125AppAdminRouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/_public/new-mobile': {
      id: '/{-$locale}/_public/new-mobile'
      path: '/new-mobile'
      fullPath: '/{-$locale}/new-mobile'
      preLoaderRoute: typeof Char123LocaleChar125PublicNewMobileRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/mobile': {
      id: '/{-$locale}/_public/mobile'
      path: '/mobile'
      fullPath: '/{-$locale}/mobile'
      preLoaderRoute: typeof Char123LocaleChar125PublicMobileRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/goodbye': {
      id: '/{-$locale}/_public/goodbye'
      path: '/goodbye'
      fullPath: '/{-$locale}/goodbye'
      preLoaderRoute: typeof Char123LocaleChar125PublicGoodbyeRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/about': {
      id: '/{-$locale}/_public/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125PublicAboutRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_auth/verify-otp': {
      id: '/{-$locale}/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/{-$locale}/verify-otp'
      preLoaderRoute: typeof Char123LocaleChar125AuthVerifyOtpRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth/signup': {
      id: '/{-$locale}/_auth/signup'
      path: '/signup'
      fullPath: '/{-$locale}/signup'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignupRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth/reset-password': {
      id: '/{-$locale}/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth/login': {
      id: '/{-$locale}/_auth/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125AuthLoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth/forgot-password': {
      id: '/{-$locale}/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth/consent': {
      id: '/{-$locale}/_auth/consent'
      path: '/consent'
      fullPath: '/{-$locale}/consent'
      preLoaderRoute: typeof Char123LocaleChar125AuthConsentRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth/complete-profile': {
      id: '/{-$locale}/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/{-$locale}/complete-profile'
      preLoaderRoute: typeof Char123LocaleChar125AuthCompleteProfileRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/app/admin/': {
      id: '/{-$locale}/app/admin/'
      path: '/'
      fullPath: '/{-$locale}/app/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AppAdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppAdminRoute
    }
    '/{-$locale}/app/profile/{-$userId}': {
      id: '/{-$locale}/app/profile/{-$userId}'
      path: '/profile/{-$userId}'
      fullPath: '/{-$locale}/app/profile/{-$userId}'
      preLoaderRoute: typeof Char123LocaleChar125AppProfileChar123UserIdChar125RouteImport
      parentRoute: typeof Char123LocaleChar125AppRoute
    }
    '/{-$locale}/app/admin/users': {
      id: '/{-$locale}/app/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/app/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125AppAdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125AppAdminRoute
    }
    '/{-$locale}/app/admin/runs': {
      id: '/{-$locale}/app/admin/runs'
      path: '/runs'
      fullPath: '/{-$locale}/app/admin/runs'
      preLoaderRoute: typeof Char123LocaleChar125AppAdminRunsRouteImport
      parentRoute: typeof Char123LocaleChar125AppAdminRoute
    }
    '/{-$locale}/_public/policy/privacy': {
      id: '/{-$locale}/_public/policy/privacy'
      path: '/policy/privacy'
      fullPath: '/{-$locale}/policy/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PublicPolicyPrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/policy/imprint': {
      id: '/{-$locale}/_public/policy/imprint'
      path: '/policy/imprint'
      fullPath: '/{-$locale}/policy/imprint'
      preLoaderRoute: typeof Char123LocaleChar125PublicPolicyImprintRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/.well-known/oauth-authorization-server/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125PublicRouteRouteChildren {
  Char123LocaleChar125PublicAboutRoute: typeof Char123LocaleChar125PublicAboutRoute
  Char123LocaleChar125PublicGoodbyeRoute: typeof Char123LocaleChar125PublicGoodbyeRoute
  Char123LocaleChar125PublicMobileRoute: typeof Char123LocaleChar125PublicMobileRoute
  Char123LocaleChar125PublicNewMobileRoute: typeof Char123LocaleChar125PublicNewMobileRoute
  Char123LocaleChar125PublicIndexRoute: typeof Char123LocaleChar125PublicIndexRoute
  Char123LocaleChar125PublicPolicyImprintRoute: typeof Char123LocaleChar125PublicPolicyImprintRoute
  Char123LocaleChar125PublicPolicyPrivacyRoute: typeof Char123LocaleChar125PublicPolicyPrivacyRoute
}

const Char123LocaleChar125PublicRouteRouteChildren: Char123LocaleChar125PublicRouteRouteChildren =
  {
    Char123LocaleChar125PublicAboutRoute: Char123LocaleChar125PublicAboutRoute,
    Char123LocaleChar125PublicGoodbyeRoute:
      Char123LocaleChar125PublicGoodbyeRoute,
    Char123LocaleChar125PublicMobileRoute:
      Char123LocaleChar125PublicMobileRoute,
    Char123LocaleChar125PublicNewMobileRoute:
      Char123LocaleChar125PublicNewMobileRoute,
    Char123LocaleChar125PublicIndexRoute: Char123LocaleChar125PublicIndexRoute,
    Char123LocaleChar125PublicPolicyImprintRoute:
      Char123LocaleChar125PublicPolicyImprintRoute,
    Char123LocaleChar125PublicPolicyPrivacyRoute:
      Char123LocaleChar125PublicPolicyPrivacyRoute,
  }

const Char123LocaleChar125PublicRouteRouteWithChildren =
  Char123LocaleChar125PublicRouteRoute._addFileChildren(
    Char123LocaleChar125PublicRouteRouteChildren,
  )

interface Char123LocaleChar125AppAdminRouteChildren {
  Char123LocaleChar125AppAdminRunsRoute: typeof Char123LocaleChar125AppAdminRunsRoute
  Char123LocaleChar125AppAdminUsersRoute: typeof Char123LocaleChar125AppAdminUsersRoute
  Char123LocaleChar125AppAdminIndexRoute: typeof Char123LocaleChar125AppAdminIndexRoute
}

const Char123LocaleChar125AppAdminRouteChildren: Char123LocaleChar125AppAdminRouteChildren =
  {
    Char123LocaleChar125AppAdminRunsRoute:
      Char123LocaleChar125AppAdminRunsRoute,
    Char123LocaleChar125AppAdminUsersRoute:
      Char123LocaleChar125AppAdminUsersRoute,
    Char123LocaleChar125AppAdminIndexRoute:
      Char123LocaleChar125AppAdminIndexRoute,
  }

const Char123LocaleChar125AppAdminRouteWithChildren =
  Char123LocaleChar125AppAdminRoute._addFileChildren(
    Char123LocaleChar125AppAdminRouteChildren,
  )

interface Char123LocaleChar125AppRouteChildren {
  Char123LocaleChar125AppAdminRoute: typeof Char123LocaleChar125AppAdminRouteWithChildren
  Char123LocaleChar125AppFeedRoute: typeof Char123LocaleChar125AppFeedRoute
  Char123LocaleChar125AppLeaderboardRoute: typeof Char123LocaleChar125AppLeaderboardRoute
  Char123LocaleChar125AppSettingsRoute: typeof Char123LocaleChar125AppSettingsRoute
  Char123LocaleChar125AppIndexRoute: typeof Char123LocaleChar125AppIndexRoute
  Char123LocaleChar125AppProfileChar123UserIdChar125Route: typeof Char123LocaleChar125AppProfileChar123UserIdChar125Route
}

const Char123LocaleChar125AppRouteChildren: Char123LocaleChar125AppRouteChildren =
  {
    Char123LocaleChar125AppAdminRoute:
      Char123LocaleChar125AppAdminRouteWithChildren,
    Char123LocaleChar125AppFeedRoute: Char123LocaleChar125AppFeedRoute,
    Char123LocaleChar125AppLeaderboardRoute:
      Char123LocaleChar125AppLeaderboardRoute,
    Char123LocaleChar125AppSettingsRoute: Char123LocaleChar125AppSettingsRoute,
    Char123LocaleChar125AppIndexRoute: Char123LocaleChar125AppIndexRoute,
    Char123LocaleChar125AppProfileChar123UserIdChar125Route:
      Char123LocaleChar125AppProfileChar123UserIdChar125Route,
  }

const Char123LocaleChar125AppRouteWithChildren =
  Char123LocaleChar125AppRoute._addFileChildren(
    Char123LocaleChar125AppRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125PublicRouteRoute: typeof Char123LocaleChar125PublicRouteRouteWithChildren
  Char123LocaleChar125AppRoute: typeof Char123LocaleChar125AppRouteWithChildren
  Char123LocaleChar125AuthCompleteProfileRoute: typeof Char123LocaleChar125AuthCompleteProfileRoute
  Char123LocaleChar125AuthConsentRoute: typeof Char123LocaleChar125AuthConsentRoute
  Char123LocaleChar125AuthForgotPasswordRoute: typeof Char123LocaleChar125AuthForgotPasswordRoute
  Char123LocaleChar125AuthLoginRoute: typeof Char123LocaleChar125AuthLoginRoute
  Char123LocaleChar125AuthResetPasswordRoute: typeof Char123LocaleChar125AuthResetPasswordRoute
  Char123LocaleChar125AuthSignupRoute: typeof Char123LocaleChar125AuthSignupRoute
  Char123LocaleChar125AuthVerifyOtpRoute: typeof Char123LocaleChar125AuthVerifyOtpRoute
  Char123LocaleChar125OauthLoginRoute: typeof Char123LocaleChar125OauthLoginRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125PublicRouteRoute:
      Char123LocaleChar125PublicRouteRouteWithChildren,
    Char123LocaleChar125AppRoute: Char123LocaleChar125AppRouteWithChildren,
    Char123LocaleChar125AuthCompleteProfileRoute:
      Char123LocaleChar125AuthCompleteProfileRoute,
    Char123LocaleChar125AuthConsentRoute: Char123LocaleChar125AuthConsentRoute,
    Char123LocaleChar125AuthForgotPasswordRoute:
      Char123LocaleChar125AuthForgotPasswordRoute,
    Char123LocaleChar125AuthLoginRoute: Char123LocaleChar125AuthLoginRoute,
    Char123LocaleChar125AuthResetPasswordRoute:
      Char123LocaleChar125AuthResetPasswordRoute,
    Char123LocaleChar125AuthSignupRoute: Char123LocaleChar125AuthSignupRoute,
    Char123LocaleChar125AuthVerifyOtpRoute:
      Char123LocaleChar125AuthVerifyOtpRoute,
    Char123LocaleChar125OauthLoginRoute: Char123LocaleChar125OauthLoginRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  DePrivacyRoute: DePrivacyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DotwellKnownOauthAuthorizationServerApiAuthRoute:
    DotwellKnownOauthAuthorizationServerApiAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
