apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
generators:
  - ksops.yaml
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - namespace.yaml
  - ingress.yaml
  - git-repository.yaml
  - applications/argocd-application.yaml
  - applications/trichter-application.yaml
  # - applications/matrix-application.yaml
  - applications/monitoring-application.yaml
  # - applications/docmost-application.yaml
  - applications/keycloak-application.yaml
  - applications/fundus-application.yaml
  - applications/hetzner-infrastructure-application.yaml
  - applications/outline-application.yaml
  # - applications/plane-application.yaml
  - applications/tools-application.yaml
  # - applications/umami-application.yaml
  # - applications/wordpress-application.yaml
  # - applications/wikijs-application.yaml
patches:
  - path: config/argocd-cm.yaml
  - path: config/argocd-cmd-params-cm.yaml
  - path: config/argocd-rbac-cm.yaml
  - path: config/argocd-repo-server.yaml
