apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - qrding-deployment.yaml
  - qrding-service.yaml
  - qrding-ingress.yaml
  - it-tools-deployment.yaml
  - it-tools-service.yaml
  - it-tools-ingress.yaml
