spring:
  profiles:
    default: local
  application:
    name: trichter-backend
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  build-id: 76787a67
  storage:
    azure:
      container-name: trichter-image
      key-prefix: runs/images

springdoc:
  swagger-ui:
    path: /api/docs
  show-actuator: true



logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
