spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    azure:
      storage:
        blob:
          container-name: ${AZURE_CONTAINER_NAME}
          connection-string: ${AZURE_STORAGE_CONNECTION_STRING}

