apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/trichter
  - ../../base/ingress
  - ../../base/linus
  - ./helmchartconfig-traefik.yaml
generators:
  - ksops.yaml
