apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
